### ISSUE TITLE
Enhancement Request: Tree harvester / planting

### ISSUE THREAD

**Issue by ozzei** [mekanism-mod/Mekanism#1630]
This request was on the minecraft forum today.

Would be great if we had some mekanism machine which would harvest wood from local trees and also planted trees/saplings.  The request made a mention of a tower looking model (would assume a sentry looking tower) or perhaps something similar to the digital miner (I suppose you could use the digital miner) but how about a sapling deployment system.

I know BuildCraft is working on a robot system which does something very similar and needs axes to chop down trees.

Sounds like a good enhancement.

**Comment by accessdenied0** [comment]
I hope this is still a thing, 

I would like to see that. Especial in the new Versions of Mekanism, which provides all sorts of new and cool machines! I think this would be a good addition!

**Comment by HappyPineapple** [comment]
Just a slap in the face realisation but could you make a lazier tree farm .

**Comment by accessdenied0** [comment]
I just want to note: its not only to farm Crops also to farm Trees...
