### ISSUE TITLE
Dimensional Stabilizer

### ISSUE THREAD

**Issue by Greylocke** [mekanism-mod/Mekanism#2204]
idea for a new Mek item: the Dimensional Stabilizer (chunk loader)

The Dimensional Stabilizer keeps world chunks loaded while players are away from he area. 
While providing the usual "chunk loader" benefits, it also has some features to make it more server friendly:
1. It requires power to operate (but power usage can be configured down to zero to override this)
2. A player detector will cause the chunk loader to only be active when the Owner or a listed player is online.
3. Separate -X/+X, -Z/+Z controls allow greater accuracy, minimizing chunks loaded unnecessarily

== GUI ==
range -X
range +X
range -Z
range +Z
area of effect indicator on/off
player detector on/off
owner name
field to type in a player name
ADD button to add a player name
DEL button to remove a player from the list
list of players to detect
redstone high/low/ignore

== Configuration ==
usageperchunk (integer) default 60 (J/s)
forcedetector (true/false) - will force all Stabilizers to be in Player Detect mode
playerlogdelay (integer) - number of seconds to wait after a player logs out before disabling the stabilizer
maxrange (integer) maximum range, in chunks, for each direction
oponly (true/false) - only Operators can use the stabiizer
maxperplayer (integer) how many Stabilizers a player can own. Default 5

**Comment by spannerman79** [comment]
Also if possible to have the option to either;
* Allow giving a max number of chunks that a user can load, being overridden via command - something like `/mek <player> chunk add|set|remove`

Or


* The ability to remove the block completely (via config preferred)

The reason for the above two is that I have two sets of users on my server. One being just members (aka freeloaders), the other being VIP who contribute towards the running cost of the server.  I have chunk loaders only available to VIP's currently.

**Comment by cleverca22** [comment]
one option would be to use minetweaker to adjust the chunkloader recipe to need (and not consume) a tabula rasa item, and then have OP's cheat one in and hand out to VIP's

**Comment by spannerman79** [comment]
> one option would be to use minetweaker to adjust the chunkloader recipe to need (and not consume) a tabula rasa item

That would make it dependant on another mod - which is not desired.

**Comment by Rayder44** [comment]
Is there really a benefit to setting the range in the direction? Perhaps just having a chunk radius setting would be better and simpler. Either that or having it as a simple/advanced settings.

Any ideas on how to handle power outages or shortages? Have an automatic reset mode? Or make it like a circuit breaker where the machine turns off in the event of power loss, and you have to turn it back on manually. Perhaps make this a setting as well?

**Comment by spannerman79** [comment]
> Is there really a benefit to setting the range in the direction

yes there is - even more so on the x or z axis.

Otherwise you'll need multi devices within each single chunk in a line..

For example, your way of thinking @Rayder44 if i wanted to keep a single line of chunks on the x (or z) axis loaded the number of chunks needed to be kept loaded would increase exponentially.  I line of 5 chunks would chunk load 25 chunks instead of just 5.  As i do run a server this is not desirable - and I do limit those sorts of chunk loaders to people that actually contribute towards running costs of the server.

Where if you take a chunk loader in the above example and it does have x/z axis options the number of chunks kept loaded is kept lower, less resources tied up server wise etc.

**Comment by Oct0bass** [comment]
I see this as a multiblock, which you fill with "loading units" or something, where the arrangement of the loading units represents the chunks to be loaded, with the center block representing the chunk the multiblock is in.  Beyond that, maybe the amount of "loading units" you stack on top of the bottom one represents the level of loading?  Here's what i see this as (example 5x5 loader):
`c`: some kind of "chunkloader casing"
`u`: loading unit
```
ccccc
ccccc
ccccc
ccccc
ccccc

ccccc
cuuuc
cuuuc
cuuuc
ccccc

(maybe a few layers more to represent how loaded they are)

(first layer again)
```
this would load the chunk the loader is in and the 8 directly around it.

**Comment by GamingZacharyC** [comment]
> I see this as a multiblock, which you fill with "loading units" or something, where the arrangement of the loading units represents the chunks to be loaded, with the center block representing the chunk the multiblock is in. Beyond that, maybe the amount of "loading units" you stack on top of the bottom one represents the level of loading? Here's what i see this as (example 5x5 loader):
> `c`: some kind of "chunkloader casing"
> `u`: loading unit
> 
> ```
> ccccc
> ccccc
> ccccc
> ccccc
> ccccc
> 
> ccccc
> cuuuc
> cuuuc
> cuuuc
> ccccc
> 
> (maybe a few layers more to represent how loaded they are)
> 
> (first layer again)
> ```
> 
> this would load the chunk the loader is in and the 8 directly around it.

I really like this idea. If possible, here some ideas for "how loaded that are"

------------------------------------------------
Level 1 (1 Loading Unit in a column):
Just Barely loaded (Tics the area, including aging animals. No tile entities are active, and no Random Tics.) (Uses 200 J/t)
------------------------------------------------
Level 2 (3 Loading Units in a column):
Loaded a little bit (Renders tile entities.) (Uses 1 kJ/t)
------------------------------------------------
Level 3 (5 Loading Units in a column):
Fully Loaded (Loaded as though a player were within 128 blocks; Grows crops and things.) (Uses 3 kJ/t)
------------------------------------------------

Of course, to balance this, an expensive recipe would likely also be required.

In addition, I feel like it might require some chemicals to remain active. If anything, please limit the ports to ~500 J/t (a perfect match for the power required, if my above system is used.)
