### ISSUE TITLE
Mekanism: Forcefields

### ISSUE THREAD

**Issue by aidancbrady** [mekanism-mod/Mekanism#3496]
A newer, better, CyanideX and aidancbrady inspired forcefield system. Complete in its own module.

**Comment by mimikal** [comment]
Cool!

**Comment by CyanideX** [comment]
I approve of this message.

**Comment by RedGuy54** [comment]
I'm confused... So Mekanism v10 is adding forcefields? Shouldn't this be a defense tech feature?

**Comment by aidancbrady** [comment]
DefenseTech will eventually be incorporated into Mekanism as its own module. I'm just starting that way with the forcefields.

**Comment by RedGuy54** [comment]
OK cool.

**Comment by CristinoValdigem** [comment]
That's very great news... After a long time without MFFS. I gonna be use force fields again to protect my builds \o/. That addiction we can experiment on mod to minecraft version 1.7.10 ??

**Comment by themechman** [comment]
I am not Barrak Obama and I approve this message.

**Comment by blockbreaker1361** [comment]
I'm on board for this one. I miss MFFS as well. If anyone can make an epic forcefield mod, it's you Aidancbrady. :)

**Comment by LogosWorks** [comment]
Gives something to spend obscene amounts of power on. 
Gives a way to protect the infrastructure supporting a reactor.
MFFS is one of those great mods that fell to time. Love to see how you implement it!

**Comment by jclendineng** [comment]
Agreed, force fields would be awesome in mek
