### ISSUE TITLE
[Suggestion] Show capacity (energy & fluids) of storage blocks in GUI

### ISSUE THREAD

**Issue by feldim2425** [mekanism-mod/Mekanism#3647]
Maybe I'm blind but the Energy Cubes and the Induction Matrix only show how much energy they are currently Storing and not how much they can store.

**Comment by Utildayael** [comment]
Not blind, I was just looking at my induction matrix thinking the same thing. Would be a nice bit to add both on the power tab [bottom left] and also on the statistics screen in the case of the matrix.

**Comment by tipilu** [comment]
I agree, it can be even shown as 
%stored%/%total capacity%

**Comment by thommy101** [comment]
Reopened as I've only done energy, not the fluids.
