### ISSUE TITLE
[1.10.2] multiblock doesn't share information across the chunk borders

### ISSUE THREAD

**Issue by rapus95** [mekanism-mod/Mekanism#3837]
we have an induction matrix that stands in 4 different chunks (unintentionally). If one clicks on a block you only get the information about in/output that occurs in the same chunk. So if you have an input in chunk X and an output in chunk Y you and click on a block in chunk Z, you won't get any information at all, if you click on a block that is in chunk X you'll only get the input and for Y you'll only get the output.

Edit: A server restart solved the problem temporarily.

Guess: chunkloading problems

**Comment by SportsFan10** [comment]
I  believe this is related to mine? #4451

**Comment by ktole1999** [comment]
rebuild in single chunk. multi block structures should never cross chunk border due to neighbor chunk load/unload behaviour

**Comment by thiakil** [comment]
I've not been able to reproduce in the latest 1.12 releases, please send a minimal test world if you are still able to reproduce
