### ISSUE TITLE
Request: Offshore wind power plant

### ISSUE THREAD

**Issue by ghost** [mekanism-mod/Mekanism#3857]
The current wind turbines are very nice. But they produce a very low amount off power.
Wouldnt it be cool if we could build a Offshore wind power plant ?
Compared to real life the current wind turbines which are built are at least 200m. 

The Windturbines should become a Multiblock structure. Making it VERY hard to build with a LOT of expensive materials. But in the end they should produce a very huge amount of power (2011 2.2 MW was the best output)

Im really tired of building Nuclear power plants. A offshore wind power plant would become a cleaner and better solution than Nuclear power ingame. (They also should be very loud! Like in real life)

Sorry for my bad english,
gamecompiler

Thanks in advance.

**Comment by VT-14** [comment]
Mekanism Wind Generators are dirt cheap and have a power output dependent on altitude.  If you place them at the build limit, each generator will make 480J/t ( ~192 RF/t) and cost nothing to keep running.  They are easily the most OP power generator in the game.

Nuclear reactors will always easily outpace wind turbines.  Nuclear reactors work on E=mc^2, where c is the speed of light (an insanely huge number).  Wind works on transferring kinetic energy, E=1/2*mv^2, where v is the wind speed (way way slower than the speed of light).  On top of that, Mekanism's reactor is a Fusion reactor, while most others are Fission based.  

I went on a massive tangent on how nuclear power works, but I doubt you actually care.  I will say that Fusion takes light elements (in this case, Tritium and Deuterium; both of which are Hydrogen with extra Neutrons), smashes them together, and get heavier elements.  The heaviest element possible from this reaction would be Iron; a 'safe' byproduct.  I think the byproduct of this particular reaction would be Helium, which is quite a safe and clean byproduct.  Plus, Mekanism makes the fuel from only solar power and water.  Mekanism's Reactor is a hyper efficient solar power plant.
