### ISSUE TITLE
[suggestion] Nitrogen chemistry for fertiliser and explosives

### ISSUE THREAD

**Issue by momerathe** [mekanism-mod/Mekanism#3907]
Chemical production lines are cool. Here are a couple of suggestions for some new ones.

Fertiliser:

For the source of nitrogen. I tried to think of how to do this without a new machine, but failed. 
Step 1: "Gas seperator" converts air into Nitrogen & oxygen
Step 2: Nitrogen + hydrogen in a chemical infuser -> Ammonia gas
Step 3: Ammonia gas in a rotary condensentrator -> Liquid Ammonia
Urea (a common fertiliser) is created by reacting ammonia with carbon dioxide. I think this can be finessed to work with the Pressurized Reaction Chamber.
Step 4: Liquid Ammonia + coal (carbon) + oxygen in a PRC -> "Chemical fertiliser" + water vapour.

"Chemical fertiliser" obviously works like bonemeal for crops, but can't be used for dyeing.

Explosives:

Same as before up to ammonia gas:
Step 3: Ammonia gas + oxygen in a chemical infuser -> Nitric oxide
Step 4: Nitric oxide + oxygen in a chemical infuser -> Nitrogen dioxide
The next step is really two steps in one, creating nitric acid with water and then nitrating an organic compound.
Step 5: Nitrogen dioxide + Water + Substrate in PRC -> explosive pellet + nitric oxide

explosives could be oredict'd with gunpowder, or used for later recipes.

**Comment by DovahOfKiin** [comment]
I'm actually trying to begin work on a mod that adds nitrogen related chemistry (and depends on Mekanism) but because of this issue, I cannot: https://github.com/aidancbrady/Mekanism/issues/3896
