### ISSUE TITLE
[Suggestion] Tritium without solar

### ISSUE THREAD

**Issue by whyoonowork** [mekanism-mod/Mekanism#3914]
It's great that the thermal evaporators can now be done without solar.  Now how about a way to make tritium without solar neutron activators?  Perhaps this can be another use of the laser system.

**Comment by system86** [comment]
maybe artificial neutron beams?

**Comment by JustinHuPrime** [comment]
Is this still of interest? As it stands, implementing this would allow for fission reactors producing Polonium and Plutonium in the End or the Nether, which doesn't seem to be wanted. Alternatively, non-solar Tritium could require end-game resources, to allow end-game players to run Polonium production in other dimensions.

**Comment by pupnewfster** [comment]
Uhh at some point I do think we are planning on removing the SNA and making things like tritium then be produced via one of the reactors or something (I forget the details), but honestly no idea I didn't even realize that we had a "feature request" project on this repo, as for the past year or two we have been using https://github.com/mekanism/Mekanism-Feature-Requests to track feature requests.
