### ISSUE TITLE
Request for in-game documentation

### ISSUE THREAD

**Issue by duncanwebb** [mekanism-mod/Mekanism#4040]
It would be great to have some in-game documentation

Multi-block structures would be much easier to construct with documentation. Immersive engineering has a neat way to show how to build multi-block structures.

When items change their name like Factory Installers now being called Tier Installers this would benefit from in-game documentation.

Processes like brine production are difficult to show with NEI and JEI would benefit too.

Thanks for the great mod, I love it.

**Comment by jammehcow** [comment]
If you went down the book path for this you could get it on spawn and could be crafted through a book/paper and osmium (shapeless).
