### ISSUE TITLE
[Request] Digital Miner Scanning Process Improvement

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [mekanism-mod/Mekanism#4174]
I'm using RF Tools Dimensions to create worlds to strip mine bare of any and all blocks.  I was using Actually Additions vertical digger for this, but your digital miner has two key advantages over it.  First, it covers four times the area.  Second, and even more importantly, it has the silk touch option.  However, as a strip miner it has one major disadvantage to the vertical digger.  It works from the bedrock up.

This means that it is incapable of mining gravel or sand, since it removes the blocks supporting them from underneath, dropping them into the already mined areas below. This also means that it is incapable of mining/harvesting flowers, shrubs, or any other block that breaks as soon as the block beneath it is removed.

What I request is **not** that you invert it's operation to work from the top down like the vertical digger.  I couldn't help noticing that when the digital digger first gets started it scans its programed area and counts the number of blocks to be harvested.  I would like for a second step to be added into this scan.  One which identifies all the 'fragile' blocks within it's area of operation and marks them for removal first, working from the top down.  This would mean that the digital miner would first mine all leaves, flowers, mine cart tracks, and other other blocks that break without support, as well as all sand, gravel, and other blocks that fall without support first, and then and only then would mine all stable blocks in whatever manner it deems best (I really find its randomly sized vertical sections approach weird, why not just do the entire bottom layer, then the next, and so on, but it really doesn't matter so long as all all the fragile blocks are taken care of first).

**Comment by BrianEdmonds** [comment]
I've only used the miner for ores, so this has not been an issue for me yet, but it does seem like a reasonable improvement to the miner's logic. Assuming it's expected to be able to mine such blocks at all. I'm skeptical of "mining" flowers, but gravel doesn't seem unreasonable.

**Comment by ktole1999** [comment]
i have never given thought to mining gravel considering how easy it is to convert from cobble via crusher. you could also run it a second time if you have the gravel filter enabled to pick up any stragglers.

**Comment by BrianEdmonds** [comment]
Fair enough, but if you're using a miner to clear an area, it would be useful. There are better tools for clearing blocks, but it's probably the best in Mekanism, so it may be the best offered by some packs.

**Comment by 7OOTnegaTerces** [comment]
With mods like Actually Additions  and Botania you wind up with various mushrooms, flowers, and trees underground, so I think that it is!  And don't forget about torches and rails from abandoned mineshafts!  And you can't fix the sand/gravel issue by simply running the miner again, because the next layer up of gravel falls down into the previously mined spot, meaning that you'd have to run it again to get that one, and again if this happens once more...   Totally NOT a solution!

**Comment by BreeOge** [comment]
I would like to see it go from top to bottom instead of bottom to top.  That would solve all the problems, and also turn lava into Obsidian for pickup by any water falling on it.  Right now I have huge obsidian veins that I have to run the machine again to get.  The gravel is more complicated than just running the machine again.  If you run it again, its gets the bottom one, they all drop then you have to run it again.. it can take many times before it gets all the gravel.

**Comment by Majora320** [comment]
I for one would love to see this implemented.
