### ISSUE TITLE
Atomic Disassembler Path Block Tweak

### ISSUE THREAD

**Issue by ajakk** [mekanism-mod/Mekanism#4464]
It has been a slight annoyance that the atomic disassembler does not have the ability to create path blocks. It would be very much appreciated to see such a feature added. I notice there are a couple of duplicate tilling settings under the "Normal, slow, etc" settings for the tools, perhaps one of those dupes could be replaced with the aforementioned tweak.

I could attempt to implement such a thing myself, but I'm curious to hear others' opinions on the issue.

**Comment by SuperFanatic** [comment]
Oh, definitely. I support this 100%. In fact, I would rather it just do path blocks *instead* of farmland altogether. Shovels? Those break every two minutes! Hoes? I still have the stone one I made on day 2!

**Comment by ToMe25** [comment]
I would do it like if there is grass it creates grass paths, but if there is dirt it makes farmland instead.

**Comment by ToMe25** [comment]
I will start implementing this now.

**Comment by pupnewfster** [comment]
> I will start implementing this now.

Make sure to do it off of the latest 1.12 branch because otherwise you will probably run into merge conflicts. Given I did a bunch of formatting cleanup yesterday.
