### ISSUE TITLE
[Feature] Sort the unsortables!

### ISSUE THREAD

**Issue by mal** [mekanism-mod/Mekanism#4584]
It'd be really useful to be able to use the logistical sorter to sort unstackable items such as weapons, armor and enchanted books. I found [this issue](https://github.com/aidancbrady/Mekanism/issues/1638) from 2014 and saw your objection to being able to simply type in an item without first having to have the item to hand.

Therefore my suggestion is a little different, rather than a text box, would be possible to have a `Finder` class that takes a reference `ItemStack` from the inventory similar to the way the `ItemStackFinder` does, but instead storing the `ItemStack` itself for comparison, instead looks up the registry name for it (i.e. `minecraft:bow`) and then uses that value to find all vanilla bows, or `minecraft:enchanted_book` to find all enchanted books? That way it should be possible to get the best of both worlds.

**Comment by thommy101** [comment]
This might be related to #4694 in which the functionality to ignore damage values if there are no subtypes (i.e. vanilla bows) is restored.
