### ISSUE TITLE
[Feature] The Robit Revolution

### ISSUE THREAD

**Issue by EvilCooky** [mekanism-mod/Mekanism#4608]
I'm sure we all love our little Robits, following us around and diligently picking up everything we drop.
But other then that and the crafting options he has, the little guy isn't that usefull.

Wouldn't it be fun to have more uses for our hard working robot friend.

My idea is mainly oriented on Thaumcrafts Golems.
The first thing, would be the building of Robits.
instead of having one type of robot, there could be various different ones, constructed from modular parts.
There can be a Robit with the legs, one with chain drive and maybe a robit with a hover modul.
His head could have various different sensors that help him in his daily tasks.
And his arms could have different tools to perform functions.

Now what could our Robits do with all of that.
They cold do your farmwork.
Transport Items through your base.
Sort items into inventories.
Activate Blocks
Fell Trees
Milk Cows and sheer sheeps
and patrol areas, fighting monsters and maybe even other players.
There can even be some mod compability with a robot that communicates with computercraft or open computers

I do realise that some of these features are already implemented in some other way and some are maybe even planed with some other machines, but it's always fun to have options.

Also, I'm sure it is especially challanging to realize complex features like this with entities.

This little piece of text is just meant to inspire some ideas and I'd love to hear some opinions on that matter.

Give Robit some love.

**Comment by BrianEdmonds** [comment]
@EvilCooky said: They cold do your farmwork. Transport Items through your base...

This sounds like the sort of thing I've done in the past with
OpenComputers.  Build and program a robot to mine for you, harvest trees
and sugarcane, etc.  Highly recommended if you want serious flexibility
in getting things automated.

**Comment by Coolfeather2** [comment]
Factorio drones?

**Comment by EvilCooky** [comment]
More like Thaumcraft golems.

**Comment by laz2727** [comment]
This is a bit too much copying TC. I could understand farming/milking/w/e robits but pipes exist (maybe area pickup robit only?) and they don't look durable enough to fight.
