### ISSUE TITLE
[1.10.2] Crash when trying to enchant an Osmium Pickaxe with silk touch book

### ISSUE THREAD

**Issue by MJRLegends** [mekanism-mod/Mekanism#4652]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
While trying to enchant an Osmium Pickaxe with silk touch book, game crashes.

#### Steps to reproduce:
1.Make Osmium Pickaxe
2. Place in an anvil with enchanted book
3. Game crashes when trying to apply the enchantment 
#### Crash log: 
https://pastebin.com/f4TVY3py

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2442
**Mekanism:** 9.2.3.97
**Other relevant version:** 

Reported to me by a player of my pack here: https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/95

**Comment by thommy101** [comment]
Cannot reproduce in latest version (1.12). Leaving this open as it might be fixed for 1.10, but don't take my word on that ;)

**Comment by MJRLegends** [comment]
It would be great if it could

**Comment by MJRLegends** [comment]
@thommy101 Dont mean to bother you again today but any news on this issue :D 

Once again thanks for your time

**Comment by thommy101** [comment]
Feel free to ask ;) I've got some time tomorrow, will see if I can backport a bunch critical fixes and see if this could be on the list of things that could be fixed :)

**Comment by MJRLegends** [comment]
Sounds good, will look forward to seeing them :D

**Comment by MJRLegends** [comment]
@thommy101 sorry to bother you but have you been able to work on some fixes. I appreciate free time is now and then and you have other commitments

**Comment by thommy101** [comment]
Sorry, I didn't have time yet.. Currently quite busy with my new job

**Comment by MJRLegends** [comment]
No worries

**Comment by MJRLegends** [comment]
@thommy101 @thiakil sorry to keep bothering you, but any news on the mc 1.10.2 dev side of things. Atm this is the only bug out standing that i've found. :D
