### ISSUE TITLE
[1.11.2] Mekanism item pipes incompatible with Storage Drawers

### ISSUE THREAD

**Issue by Dragnier** [mekanism-mod/Mekanism#4653]
#### Issue description:
Mekanism item pipes and machines do not recognize Storage Drawers; they will not output to or retrieve from any storage drawers. Many other modded item pipes work with Storage Drawers just fine, but I don't want to need other mods besides Mekanism just for pipes. Storage Drawers are cheaper to make, less lag/fps issues, and more configurable than Bins; otherwise I'd use those instead.

#### Steps to reproduce:
1. Place a storage drawer.
2. Place a Mekanism machine or item pipe next to that storage drawer and try to configure it to output to or draw from that drawer.
3. Nothing happens, pipes won't even show a connection.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.11.2 - 13.20.1.2454
**Mekanism:** 1.11.2 - 9.3.4-fix
**Other relevant version:** Storage Drawers 1.11.2 - 4.2.10

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No crash, just doesn't work.

**Comment by thommy101** [comment]
Already thought it looked familiar. Also reported at #4516 but that one has been closed incorrectly.
Thanks for reporting!

**Comment by Akarys42** [comment]
Still occurs in 1.15.2

**Comment by pupnewfster** [comment]
It isn't an issue on our end #5957
