### ISSUE TITLE
Feature request : Jetpack gliding

### ISSUE THREAD

**Issue by LordHellscream** [mekanism-mod/Mekanism#4705]
I believe this has been asked in the past and was told this was being looking into, is this still the case? Would love to have this feature.

**Comment by thiakil** [comment]
What exactly do you mean by gliding?

**Comment by LordHellscream** [comment]
Basically a fast way to travel using the jetpack (fast forward motion).

**Comment by kraft2004** [comment]
That would be extremely handy. I only use Mek's Jetpack early-game and when I'm doing a Mek playtrough because of that reason.

**Comment by LordHellscream** [comment]
there is actually a way for fast-travel but it will be so much cooler with built-in gliding/jet option.
The way I do it is use the slime sling of tinker construct to shoot me to the air then turn around and keep going with jetpack it's pretty fast.

**Comment by Smiley43210** [comment]
As another workaround, again with Tinkers Construct, using the slime boots, you have to bounce at least once, and then fly with the jetpack. This will allow you to have the mid-air speed of the slime boots and the flight of the jetpack. This is how I get around quickly and easily.
