### ISSUE TITLE
JEI integration filters

### ISSUE THREAD

**Issue by thommy101** [mekanism-mod/Mekanism#4756]
#### Issue description:
JEI has the option to transfer recipes (`IRecipeTransferHandler`). It would be nice to use this to fill in item filters used by the logistical sorter & digital miner.

#### Steps to reproduce (the wanted result):
1. Open Logistical Sorter
2. Add new ItemStack filter
3. Select desired item to filter in JEI
4. Click the + icon
5. See the `ItemStack` appear in the top left slot

#### Needed functionality:
Somewhere in MekanismJEI needs to be the following call:
`registry.getRecipeTransferRegistry().addUniversalRecipeTransferHandler(......)`

An `IRecipeTransferHandler` which is specific for the item filters.

The problem why this is an issue and not something I've already implemented:
It only works with classes extending `Container`, which there isn't. All needed for the filters are some GUI's to set stuff up, and a list in the tile entity storing all the filters, there isn't a part in between which could store stuff (a container).

Opened for discussion as I'm not sure this is (without to much problems) possible.

**Comment by josephcsible** [comment]
For reference, here's how Integrated Dynamics does it with its logic programmer: https://github.com/CyclopsMC/IntegratedDynamics-Compat/blob/8417e00c478781543b7d12f2cfaad921a089fed3/src/main/java/org/cyclops/integrateddynamicscompat/modcompat/jei/JEIIntegratedDynamicsConfig.java

**Comment by thiakil** [comment]
Something to consider:

>I think I'm going to just maintain the OreDictionary filters - the reason I haven't added this in yet is I feel that being able to type in the name of any block you want to replace would kind of take away from the fun of the different filters - the OreDictionary filters are great for dealing with wide varieties of blocks, but when you want to get specific, you need to have the type of block on hand. Hope you understand!

https://github.com/aidancbrady/Mekanism/issues/1638#issuecomment-51282193

**Comment by josephcsible** [comment]
I think it's worth reconsidering that. It really seems to decrease convenience without adding any real challenge.

**Comment by thiakil** [comment]
Well you can't really decrease convenience that's not there in the first place - but I'm not arguing that it wouldn't add convenience. 

Indeed it's not a huge challenge to get the item to put in but typing or selecting stuff would make the DM even more of a magic 'press button, insert power, get thing'

At the end of the day it's not my call, I just wanted to point out what has been said in the past.
