### ISSUE TITLE
Provide more powerful transportation methods

### ISSUE THREAD

**Issue by dav20011** [mekanism-mod/Mekanism#4759]
It's currently impossible to transport the energy produced by reactors/turbines with universal cables. The only workaround is to directly connect it to an induction cell. It's also pretty much impossible to transport or even get enough water for larger turbines.

I'd suggest to either improve the transport/pump rates or to add higher tiers.

**Comment by thommy101** [comment]
What do you mean with "impossible to transport the energy produced by reactors/turbines"? The ultimate universal cables have such high throughput that it should be more than enough. The "problem" is often that people do not know how the cables from Mekanism work, they have a larger throughput the larger the cable network is.

The values for throughput are by the way already configurable.

**Comment by dav20011** [comment]
I know that, but that would mean that you have to create a network of ~1000 cables just to transport the energy from a turbine. Thermal Dynamics in the other hand provides a solution that is expensive, but much more intuitive. Btw the pump rate doesn't scale up.

It's also clear that there is a config, however the default config should be balanced to the mod itself, which it is not.

**Comment by zashra00** [comment]
Well  a ultimate universal cables default is 320,000 joules or 128,000 rf per cable... so unless your reactor is making 128,000,000 rf or 320,000,000 j you would never need ~1000 cables

**Comment by dav20011** [comment]
Not the reactor. The turbine can generate up to 100MRF per tick without problems.

**Comment by thiakil** [comment]
The point is that you *need* a boatload of cables to satisfy the output if you want to use Mekanism.

*It is not meant to be easy*

**Comment by dav20011** [comment]
That's just not a very good way of making it harder. If I want to connect a turbine with a matrix, I have to place a giant cube of cables? Why not just add a more expensive cable?

By the way it doesn't even make it harder. Crafting those cables is easy and I always have huge amounts of resources (digital miner). The only thing this system does is making it ugly and annoying to use.

**Comment by thiakil** [comment]
> Why not just add a more expensive cable?

Because that's the way it was designed. Don't like it, use some other mod's cables.

> Thermal Dynamics in the other hand provides a solution that is expensive, but much more intuitive.

expensive in what way?

**Comment by dav20011** [comment]
I know this is the way how it is designed, but those cables were not intended for the turbine and thus don't fit well. Do you really think that it is a good idea to make a 10x10x10 clump of cables necessary?

Cryo Stabilized Fluxducts require more effort to produce (Enderium, Magma Crucible, Fluid Transposer) and you need to kill a lot of Endermen and Blizzes. In Mekanism you can get all the necessary resources by pressing a button.

**Comment by zashra00** [comment]
I see... so then what's the issue? The free mod that no one is forcing you to use doesn't meet your standards? If the only complaint is that you can't transfer that ungodly amount of energy that you'll never use then the only real issue I see is your self entitled opinion on how the mod, again that no one is forcing you to use is somehow lacking

**Comment by thiakil** [comment]
You also don't have to use the cables. You can have multiple reactor ports and multiple entangloporters for instance.

And a 10x10x10 clump is by far not the only option. Increase the distance between them, with like a 5 x N x 1

**Comment by zashra00** [comment]
Well shoot... if you're going all out with the cables might as well make them look cool with a fancy design

**Comment by dav20011** [comment]
That would require a bunch of Quantum Entangloporters. What you mention are just workarounds for a balancing issue.

**Comment by thiakil** [comment]
Well it's actually an alternative for you not wanting to use the cables as designed (creating a large cable network) or just connecting the Storage medium directly.

The throughput is configurable, and things like Minetweaker exist if you don't like our balancing. The fact is that you still require extra machines to do the infusing, just no mob grinder. On that note, Ender Pearls are for teleportation - if a mod uses them to make maximum throughput it's just silly imo.

Regardless of what arguments you make, new power transport options are unlikely to exist before Mekanism v10; we have many other things to attend to first.

**Comment by zashra00** [comment]
Preach it
