### ISSUE TITLE
Enhancement request: Some kind of powered home defense system

### ISSUE THREAD

**Issue by LordHellscream** [mekanism-mod/Mekanism#4760]
Mekanism is my favorite mod of all time. Will be cool if some kind of home defense system can be added ?
With all the cool RF generation, it will be great to have more cool stuff to spend the extra energy on.

- Laser turrets (tiered upgrades using installer for increased damage/fire rate)
- Laser fences (electrocute things and set on fire when passing through)
- Ion Cannon - radius blast, stun/freeze creatures 

Thanks and keep up the great work

**Comment by thiakil** [comment]
See https://github.com/aidancbrady/Mekanism/issues/3496#issuecomment-233405885 & #3108 I guess

**Comment by ouroborus** [comment]
@LordHellscream Don't we already have laser fences via lasers and laser amplifiers? No fire or electrocution, just rapid or instant death depending on charge levels. Enough charge will even insta-kill players in Draconic armor.
