### ISSUE TITLE
[Suggestion] Separate wires without covers

### ISSUE THREAD

**Issue by Discomanco** [mekanism-mod/Mekanism#4781]
Like with (almost) every other mod that brings a item transfer/logistic cable, make them disconnect from each other with a wrench.
You can already set the connections to do PULL/PUSH/NONE, but those don't work on wire-to-wire connections, so why not have them disconnect when either side is set to NONE? Maybe even have them respect PULL/PUSH as well when connected to other wires. Would give a lot of options when making the wires.

The reason I'm asking for this is due to a current bug with MCMP (or C&B?) causing crashes (https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310). While it is going to get fixed eventually (hopefully), it could happen again, and always nice with options.

**Comment by EliogabalusPL** [comment]
It's an interesting idea. All the more, unfortunately, there is no function of configurator designed to disconnect or change direction at the junction of pipes / wires.
This function only works on pipe / pipe ends, which sometimes causes a lot of irritation when you want to let go of two pipes of the same color, but you do not want to connect.

**Comment by Lukas45** [comment]
Which is exactly why I'm suggesting it.
Its a thing with Thermal Expansion, BuildCraft, EnderIO, ExtraUtilities, Embers, XNet and probably many more mods which introduces any kind of wire/pipe. The only I can think of that doesn't, is Applied Energistics, but they come with their own, in-mod separators in the form of Quartz Fiber and Cable Anchors.
And the color is a only a solution when working with items. Doesn't work with Fluid/Gas/Heat/Power lines

**Comment by PapiDimmi** [comment]
I agree! That’d be great.

**Comment by pupnewfster** [comment]
This got implemented in 9.7.2 (it is now possible to separate pipes using the configurator)
