### ISSUE TITLE
[Suggestion] [1.12.2] Add Muffling Upgrade to Logistical Sorter

### ISSUE THREAD

**Issue by Skyler-Altol** [mekanism-mod/Mekanism#4813]
The title basically says it all. Would it be possible to add upgrade functionality to the logistical sorter, so that we could use muffling upgrades in it? The consistent clicking while its working may be nice for some, but it would be nice to be able to have a choice in the matter :)

Cheers.

**Comment by GGG-KILLER** [comment]
If possible could the logistical sorter also be made to accept speed upgrades?

My mob grinder is being slowed down by the logistical sorter not taking items out of the chest fast enough and the items that aren't picked up are sometimes being deleted by the server because of the delay.
