### ISSUE TITLE
Logistical sorter round robin limit

### ISSUE THREAD

**Issue by BaneOfSerenity** [mekanism-mod/Mekanism#4817]
MC: 1.12.2
Forge: 14.23.0.2515
Mek: 9.4.1

I noticed when trying to RR with the LS it tries to RR a stack at a time. I would be nice to be able to set this to RR 1 item at a time in order to correctly fill multiple machines at a time when you only have enough items to partially fill multiple machines.

**Comment by Zajozor** [comment]
I could look into this, if it is still requested. I looked through the code and it seems like something I should be able to grasp. Should the issue be reopened/shall I create a new one, or just submit a PR?

**Comment by thiakil** [comment]
Just a PR is fine :)
