### ISSUE TITLE
BC Energy Compatibility

### ISSUE THREAD

**Issue by fmohican** [mekanism-mod/Mekanism#4821]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism pipe's won't connect to quarry or other BC machine's

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.0.2529
**Mekanism:** 9.41.326
**Other relevant version:** BuildCraft 7.99 [BC 1.12](https://www.mod-buildcraft.com/buildcraft-79912-alpha-buildcraft-79981-alpha-buildcraft-7123-stable-buildcraftcompat-717-stable-buildcraftcompat-7990-alpha.html)

**Comment by PapiDimmi** [comment]
@aidancbrady Since [Buildcraft](https://www.reddit.com/r/feedthebeast/comments/7ezn3t/buildcraft_1122_alpha_released/) exists for 1.12.2 now, can you please add compatibility with its Minecraft Joules?

**Comment by thiakil** [comment]
We will be looking into it soon. It's only just released and is still alpha, so please be patient,

**Comment by thiakil** [comment]
Ok, so I have looked into this a little, and it seems there never was actual Buildcraft MJ integration; it would have just been using the RF compatibility. Will have a chat to the BC guys though.

**Comment by fmohican** [comment]
any news ?

**Comment by Ghent** [comment]
I too am excited for this.  Updating post to add the word quarry (instead of the misspelled 'query' so search engines will find this issue. ;)

**Comment by fmohican** [comment]
@Ghent  my bad, query is a php function, i'm sorry xD
thanks 👍

**Comment by Jose76Tron** [comment]
any news on this?

**Comment by fmohican** [comment]
@thiakil any news ?

**Comment by collinator24** [comment]
Hope this gets fixed soon!

**Comment by collinator24** [comment]
@thiakil any news?

**Comment by thiakil** [comment]
No, please stop asking.

Personally I don't agree with it as BC J is kinetic energy, not electromagnetic. Just use BC as the authors intend. When they've finalised their redesign we can see what is appropriate.

**Comment by fmohican** [comment]
as you said is your own opinion. from my point of view the compatibility
should exist between this two mods

**Comment by Too-DAMN-Much** [comment]
need this as a feature as well.

**Comment by codydbgt** [comment]
so this would be a no ..

**Comment by thiakil** [comment]
Buildcraft is still in alpha.

**Comment by codydbgt** [comment]
well the quarry works so ... good enough for me :D

**Comment by Too-DAMN-Much** [comment]
there's no worthwhile power generation for BC at the minute.......

**Comment by evanleeturner** [comment]
Only reason I even use BC is for the quarry !!- maybe a commonality in most folks using Mekanism & BC.  

As a code dev I can totally relate to the concept of "use our own codebase" and not inter operate with others.  I also see the point of the Mekanism developers not wasting time on creating code to work with another codebase in alpha stage.  

So instead what would be really nice out there?? A mod that is ONLY a quarry/mining item that can play nice with power & transport blocks from our favorite packages.

**Comment by Too-DAMN-Much** [comment]
@evanleeturner one of the explicit purposes of mekanism's "universal" pipes power wires was their ability to convert easily to almost any type of power, not exactly useful without the conversion part, that's all.

that was the selling point that got me on board anyway.

**Comment by thiakil** [comment]
It never actually did BC joules, only rf

**Comment by thiakil** [comment]
When I went far back in git history it didn't, and I wasn't around back then

**Comment by Too-DAMN-Much** [comment]
@thiakil regardless you literally could not be anymore wrong, i have been around since the comments were closed on notch's blog to the margin.

**Comment by Panderine** [comment]
This is marked as done but I still cannot connect universal cables to BC Quarry. Am I doing something wrong? Or Quarry won't work with mek's cables? Aren't they MJ compatible?

**Comment by pupnewfster** [comment]
This is not marked as done, it was closed and condensed into a condensed feature request list. Either way this is not going to happen due to buildcraft no longer supporting forge in 1.15, and instead switching over to fabric.

**Comment by Panderine** [comment]
Oops I took the checkmark in that list as done. Thanks for the answer!

**Comment by komega13** [comment]
Sevtech modpack only provide the basic redstone engine to power the Quarry (no stirling, no steam,   no combustion engine...) even into the late/endgame . Wich is really sad when you have whole your system turning into "universal" cable but cannot connect the Quarry

**Comment by thiakil** [comment]
1.12 is no longer supported, and buildcraft is not currently available in 1.15 - there is no point arguing this.
