### ISSUE TITLE
Mekanism machines do not idle properly when they are full

### ISSUE THREAD

**Issue by Xiaminou** [mekanism-mod/Mekanism#4899]
#### Issue description:
I have been using [LagGoggles](https://minecraft.curseforge.com/projects/laggoggles) around my base to track down what might be slowing down my server and I noticed this:
When a machine's output is full and it still has items to be processed in its input it will not idle.

Idle without items:
![2018-01-04_14 08 57](https://user-images.githubusercontent.com/8670392/34565108-da1ce33c-f159-11e7-940b-768ff35d8b48.png)
Processing items:
![2018-01-04_14 09 47](https://user-images.githubusercontent.com/8670392/34565184-13e8372e-f15a-11e7-914c-f6bcc1765a90.png)
![2018-01-04_14 09 49](https://user-images.githubusercontent.com/8670392/34565120-e5e9bfd2-f159-11e7-9f49-349b52976d7e.png)
Not processing items because output is full, but not idle:
![2018-01-04_14 11 14](https://user-images.githubusercontent.com/8670392/34565172-0ad4d732-f15a-11e7-8f92-36ef97385519.png)
Idle because no input:
![2018-01-04_14 11 23](https://user-images.githubusercontent.com/8670392/34565195-2017c0be-f15a-11e7-91fa-3a30c32e75bc.png)
![2018-01-04_14 11 46](https://user-images.githubusercontent.com/8670392/34565196-202dd228-f15a-11e7-91bc-ed55bd835bce.png)

#### Steps to reproduce:
1. Fill a machine's output and input

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2183
**Mekanism:** 330
**Mods:** [list.txt](https://github.com/aidancbrady/Mekanism/files/1603413/list.txt)

**Comment by thiakil** [comment]
What exactly is the coloured thing measuring?

**Comment by L-Clouds** [comment]
Based on the modlist provided in the report, it's the mod LagGoggles, which uses a colored overlay and floating text (which you can see in the screenshots reporting times in microseconds).  Per LagGoggles' description on CurseForge: 
>Entities are timed using System.nanotime() before and after the tick() and update() methods. These times are being recorded and sent to all online operators when the profiler is done.

**Comment by Xiaminou** [comment]
Woops, I forgot to confirm the edit where I added:
"I have been using [LagGoggles](https://minecraft.curseforge.com/projects/laggoggles) around my base to track down what might be slowing down my server and I noticed this:"

**Comment by roboderpy** [comment]
![what](https://i.dbot.serealia.ca/2018/04/javaw_2018-04-20_18-12-16.png)

**Comment by thiakil** [comment]
What does the percentage mean? Percentages usually go up to 100 only

**Comment by roboderpy** [comment]
[mekanism.zip](https://github.com/aidancbrady/Mekanism/files/1931987/mekanism.zip)

Contains nps snapshot to be viewed in VisualVM

**Comment by thiakil** [comment]
@roboderpy that nps suggests you have Auto Eject turned on and most of the time is spent there calculating a route.

**Comment by roboderpy** [comment]
I know. But the problem is - this lag does happen only with mekanism logistical transporters, having eject on and have Item Lasers/TE Pipes/etc attached produce no lag on each factory eject.

**Comment by thiakil** [comment]
You're still trying to pin it on the factory, when its not the factory. Pathfinding is a very expensive operation

**Comment by roboderpy** [comment]
Yes but why it recalculate path every time? And im not trying to pin it on factory. Even without eject turned on factory is still creating huge tick time lag compared to other's mod machinery. (one factory on average create 1000 microseconds vs other's average 60 microseconds at the worst)

**Comment by thiakil** [comment]
I didnt write the Transporter code. But it still has to check all the possible endpoints for one that can accept the item. In your case it spends a fair chunk of time on ItemStack capabilities due to Cyclops.

Ok, show me an NPS without eject.

**Comment by roboderpy** [comment]
Will do tomorrow, it is almost 22:00 for me

**Comment by roboderpy** [comment]
18 factories (which is less likely to occur on regular server, each player at least have 30 factories, which 9 of them are most likely continuously working)
[mekanismlagg.zip](https://github.com/aidancbrady/Mekanism/files/1944916/mekanismlagg.zip)
![2018-04-25_06 16 48](https://user-images.githubusercontent.com/6339511/39218733-56f1fdd2-4850-11e8-884a-c2f2141b6bbe.png)
![javaw_2018-04-25_06-17-48](https://user-images.githubusercontent.com/6339511/39218747-68371992-4850-11e8-8363-30895dc9b6f3.png)

Test conditions - elite factories without any upgrades, eject off, autosort on, recipe - oredict (oreAustralium)

For comprasion
[mekansim_lag2.zip](https://github.com/aidancbrady/Mekanism/files/1944949/mekansim_lag2.zip)
![javaw_2018-04-25_06-32-54](https://user-images.githubusercontent.com/6339511/39219065-849d3a74-4852-11e8-881e-e25bc763b1cd.png)
![2018-04-25_06 30 52](https://user-images.githubusercontent.com/6339511/39219066-87774f50-4852-11e8-9a96-eab9ac6a49ba.png)
Pulverisers were doing the same job as Enrichment Chamber

**Comment by thiakil** [comment]
> please pleeeease stop arguing and face the performance of Mekanism machinery. They DO create lags. And i know a bunch of server owners who are not installing Mekanism only because of lag

I'm simply asking you to provide the necessary data for your situation.

**Comment by thiakil** [comment]
I've added some caching to the recipe lookup, this should be less of an issue in the next release.
