### ISSUE TITLE
Logistical sorter pulls out whole stack of items and sends it to a full machine > items gone

### ISSUE THREAD

**Issue by victoroos** [mekanism-mod/Mekanism#4927]
Hello all

So, second issue (I'm taking server maintaining a but more serious this time, haha)

As the title says, I'm having a problem where I, e.g.. Want to smelt sand to glass, and lets say, 2 stacks. Instead of the sorter checking whether the machine is working already / is full it sends the whole 2 stacks to the energized smelter, which in the process removes 1 stacks, because smelter doesn't know what to do with it.
Is this an error on my side / how can I (temp) fix this?

vkr
victor

**Comment by thiakil** [comment]
> which in the process removes 1 stacks

please clarify.

also put all your versions here. needs to be in the same place as the issue as they are looked at per issue, not per submitter

**Comment by victoroos** [comment]
Ehm, I explained It I thought in the post itself?

And the versions, sorry, you are right:
Checked, sorry:
Mc: 1.10.2
Forge: forge-1.10.2-12.18.3.2477
Mekanism: 1.10.2-9.2.3.97

**Comment by Ricket** [comment]
Sounds the same as #4909

**Comment by victoroos** [comment]
Almost, because they aren't being dropped on the ground, the animation moves them into the machine and that is it. In the chest attached to the sorter there is a ghost item with a red 0 as counter, but the item are gone
