### ISSUE TITLE
Missing Texture on Cable?

### ISSUE THREAD

**Issue by ghost** [mekanism-mod/Mekanism#4928]
![fasf](https://user-images.githubusercontent.com/24831406/35587415-cd8fcc3c-060e-11e8-8659-fb0c885c2b90.PNG)
why you didnt add texture for that side of the cables? :D it would be good for someone like me using it like that...thanks

**Comment by thiakil** [comment]
Back faces often don't have a texture, even on vanilla blocks

**Comment by kenijey** [comment]
but that galacticraft cable has :D ... my opinion is it could have a nice texture for that side... itd be good
