### ISSUE TITLE
Copy bug using Chemical Washer in 1.10.2

### ISSUE THREAD

**Issue by 1125251807** [mekanism-mod/Mekanism#4935]
“Please use the search functionality before reporting an issue. Also take a look at the closed issues!”
I search and look this #4526 #4673 
**Issue description:**
Copying using ChemicalWasher

#### Steps to reproduce:
[https://github.com/aidancbrady/Mekanism/issues/4526](url)
[https://github.com/aidancbrady/Mekanism/issues/4673](url)
> 1.Open chemical washer gui
> 2.Place stackable item in first slot in hotbar
> 3.Hold shift and click on this item

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.10.2-forge1.10.2-12.18.3.2511
**Mekanism:** 1.10.2-9.2.3 and 9.2.4
**Other relevant version:** MCMultiPart 1.4.0,only mekanism

Fix this in 1.10.2 Pls :)

**Comment by thiakil** [comment]
we're only fixing crash bugs in 1.10, and even that has been lax of late

**Comment by clienthax** [comment]
https://github.com/aidancbrady/Mekanism/pull/5214
