### ISSUE TITLE
Reactors+ Accelerators+ Compatibility

### ISSUE THREAD

**Issue by CTH999** [mekanism-mod/Mekanism#4950]
So, you have fusion reactors, but what about:
Fission Reactors
And particle accelerators for materials (I.E. Antimatter, for bombs and a highly dangerous and effective Antimatter Reactor!)

Also, what about more compatibility?

(I.E [Draconic Evouloution](https://github.com/brandon3055/Draconic-Evolution/issues) (Especially This one [Cross-Mod Fusion Upgrades](https://github.com/brandon3055/Draconic-Evolution/issues/1050)) Also, what about [Modular Powersuits](https://minecraft.curseforge.com/projects/modular-powersuits?gameCategorySlug=mc-mods&projectID=235442)?) (Here [Especially](https://github.com/MachineMuse/MachineMusePowersuits/issues/832)) (Once they update!)

However, this is just an idea. It's your mod. (Last time I checked that is)

**Comment by CTH999** [comment]
@thiakil Thanks!

**Comment by MarshTheBacca** [comment]
I would love to see a more modernised version of Big Reactors which was quite poorly ported to 1.12.2 under the name Extreme Reactors. Reproducing the reactor multiblocks with mekanism units and crafting recipes would be great.
