### ISSUE TITLE
CTM breaking multiblock textures

### ISSUE THREAD

**Issue by LazyDope** [mekanism-mod/Mekanism#4970]
#### Issue description:
Connected Textures when used with Chisel and Optifine, causes multiblock structure block's textures to be black and purple

#### Steps to reproduce:
1.Place Thermal Evaporation Plant blocks
#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.1.2600** 
**Mekanism: 1.12.2-9.4.3.330** 
**Optifine: 1.12.2_HD_U_C8** 
**CTM: MC-1.12-0.2.3.12** 
**Chisel: MC-1.12-0.1.1.26** 

With out Chisel and/or Optfine (It's fine with just one or the other)
![2018-03-10_12 38 47](https://user-images.githubusercontent.com/27651460/37245154-0c29cdfa-2462-11e8-8706-f13518bd91eb.png)

With Both Chisel and Optifine
![2018-03-10_12 37 12](https://user-images.githubusercontent.com/27651460/37245152-08140852-2462-11e8-81ef-253e17a48f18.png)

Disabling CTM rendering in the Mekanism configs doesn't affect anything, and is the only multiblock mod affected.
The logs don't have anything involving CTM or Mekanism either

**Comment by thiakil** [comment]
I dont think there's anything we can do, report to CTM and Optifine

**Comment by thommy101** [comment]
Linking to https://github.com/Chisel-Team/ConnectedTexturesMod/issues/43

**Comment by ThePuzzlemaker** [comment]
In 1.12.2, with the below versions, the problem seems to be fixed.
CTM: MC1.12-0.2.3.12
Chisel: MC1.12.2-0.2.0.31
Mekanism (Core, Tools, and Generators): 1.12.2-9.4.10.345
Optifine: 1.12.2_HD_U_D3
