### ISSUE TITLE
[1.12.2] Digital Miner Blank Screen

### ISSUE THREAD

**Issue by fmohican** [mekanism-mod/Mekanism#4971]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When i try to click "Visuals" from the GUI, minecraft window going blank. I attach the SS
https://user-images.githubusercontent.com/17950489/37245040-009103e4-249b-11e8-8a3d-74febe8d5622.png
#### Steps to reproduce:
1. Open Digital Miner Interface
2. Click on "Visuals" (button on the left top form the GUI)
3. Puff Minecraft going in blank screen

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.2.2624
**Mekanism:** 1.12.2-9.4.3.330
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

isn't

**Comment by thiakil** [comment]
First try disabling *any* rendering mods, if still persists, post full modist with versions

**Comment by fmohican** [comment]
Yap, it's caused by "BetterFPS"
I will open issues on BetterFPS Git.

**Comment by TheSnowyChickens** [comment]
Hello,

I have an "better" version from this bug ^^

I call it "Light blue screen" :D
![2018-04-08_02 50 00](https://user-images.githubusercontent.com/29357962/38461717-a1d2d708-3ad7-11e8-9ba6-3fe90128facc.png)

**Comment by thiakil** [comment]
Unless the betterfps guys can tell us what we're doing wrong, we can't do anything
