### ISSUE TITLE
[suggestion]About make laser more friendly for other players on server

### ISSUE THREAD

**Issue by Tollainmear** [mekanism-mod/Mekanism#4981]
#### Issue description:
  Hi~ Mekanism was a nice mod that bring us joy, but also has troubles which caused by lasers.

  I have setup a server to play mekanism with my friends, and we also welcome strangers to join us, but there were some player use laser unfriendly, such as digging around other's house, which broken was unable to prevent by plugins(Sponge plugins, such as griefrevention which could only cancel break event caused by players).

  but mek's laser was so cool ( active nuclear generator and transport RF) that we don't want to set it unavailable, so I'm here to request a suggestion:
  How about to give more configurable node to laser or other blocks which would be used by someone unfriendly to break other's homes? and if we could config it to disable laser to damage player would much better. even if there were no such friendly laser in real life 😅
  Thanks for checking out. ;)

#### Version :
Minecraft Forge: 14.23.2.2611
Mekanism-1.12.2-9.4.3.330
**Other relevant version:**

**Comment by josephcsible** [comment]
It seems like the laser can already by stopped by canceling the `BlockEvent.BreakEvent` that it fires: https://github.com/aidancbrady/Mekanism/blob/07aab3bd2052209b41020e83f5251ea3690b2170/src/main/java/mekanism/common/LaserManager.java#L90-L96

**Comment by thiakil** [comment]
There also appears to be a setting just above that to turn block breaking off completely

```
if(!general.aestheticWorldDamage)
{
	return null;
}
```

So Enhancement is for turning off player damage.
