### ISSUE TITLE
Suggestion:Water Stuff 

### ISSUE THREAD

**Issue by Wotzinator** [mekanism-mod/Mekanism#4986]
so 1.13 will be out soon and if this mod updates to that version i would suggest adding more stuff to oceans like submarines ore something that has todo with corals or a water scouter.

**Comment by raspopov** [comment]
Everybody wants a single ultimate item - a combined [Scuba Tank](http://wiki.aidancbrady.com/wiki/Scuba_Tank) with [Jetpack](http://wiki.aidancbrady.com/wiki/Jetpack)/[Armored Jetpack](http://wiki.aidancbrady.com/wiki/Armored_Jetpack)!

Mekanism Underwater Animal Testing:
![Scuba Cat](https://s.hswstatic.com/gif/scuba-cat-6.jpg)

**Comment by Wotzinator** [comment]
um ok
