### ISSUE TITLE
After the updates the last few days the Atomic Dissasembler quit chopping BOP trees in vein mine mode.

### ISSUE THREAD

**Issue by ProsperCraft** [mekanism-mod/Mekanism#5024]
#### Issue description:
After we updated you can no longer vein mine Biomes O Plenty trees with the Atomic Dissasembler.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.3.2655-universal
**Mekanism:** Mekanism-1.12.2-9.4.4.339
**Other relevant version:** 

Modpack - https://minecraft.curseforge.com/projects/towncraft

**Comment by thiakil** [comment]
which trees specifically? Pine worked just fine in my tests just now

**Comment by ProsperCraft** [comment]
Willow Sapling from Biomes o plenty.
Fir wood from Biomes o plenty.
Jacaranda wood  from biomes o plenty.


Rubber wood from Ic2(never did work previously)
