### ISSUE TITLE
Actual color of oxygen

### ISSUE THREAD

**Issue by Cbert** [mekanism-mod/Mekanism#5028]
I’ve been pleasantly surprised when I discovered for myself real color of oxygen, it looks like sky.
Let’s not waste opportunity of showing real color of oxygen to mod users around the world.
Actual color of oxygen: https://upload.wikimedia.org/wikipedia/commons/c/c3/Liquid_oxygen_in_a_beaker_4.jpg
google search query “oxygen in a beaker”

Not this color that in use
![2018-04-28 18 22 52](https://user-images.githubusercontent.com/9320867/39398095-78c6c474-4b11-11e8-866b-5851be71b55b.png)

**Comment by Cbert** [comment]
Independent source https://youtu.be/8mk4Q5omv3Q?t=1m51s

**Comment by raspopov** [comment]
I tried it:

![New Colors](https://user-images.githubusercontent.com/228064/39803838-f5fa99ae-537a-11e8-915a-82787ead3ab7.jpg)

1 - New Oxygen. Sky Blue.
2 - New Chlorine. In fact it has a yellow-green color.
3 - New Tritium. It was blue and now looks like a new oxygen so I changed it to most recognizing color of tritium tubes i.e. glowing green.

Oxygen:
![Oxygen breaker](https://user-images.githubusercontent.com/228064/39804446-aed9c912-537c-11e8-82cf-3c1c5a0b7569.jpg)

Chlorine:
![Chlorine ampule](https://user-images.githubusercontent.com/228064/39804445-aeb43a76-537c-11e8-82c9-fbbbeccbd86d.jpg)

Tritium:
![Watch with tritium-illuminated face](https://user-images.githubusercontent.com/228064/39804444-ae90b754-537c-11e8-9ddf-65df04358461.jpg)

**Comment by Cbert** [comment]
@raspopov "4- New Lithium. It was yellow-green so I make it more orange as one of its mineral form (Lithium petalite)."
Actually it’s a lithium petalite.
https://www.123rf.com/photo_24392938_petalite-also-known-as-castorite-important-ore-of-lithium-isolated-on-white.html
Real color of lithium is: https://upload.wikimedia.org/wikipedia/commons/a/ae/Lithium_paraffin.jpg (Lithium floating in oil)
«In moist air, lithium rapidly tarnishes to form a black coating» en.wikipedia.org/wiki/Lithium

**Comment by raspopov** [comment]
Many metals has white metallic color. :-)
