### ISSUE TITLE
Formulaic Assemblicator does not automatically reuse non-consumable when crafting

### ISSUE THREAD

**Issue by Equanic** [mekanism-mod/Mekanism#5041]
Issue description:
Formulaic Assemblicator does not reuse non-consumable when crafting. This may not be a bug, but when I place the non-consumable crafting items from Harvestcraft (mortar and pestle, bakeware, pot, ect.) as part of the recipe, the device moves the non-consumable to the output.

Steps to reproduce:
1. Place wheat and mortar and pestle into the powered Formulaic Assemblicator so that the interface produces a green check in place of a red x.

2. Place blank crafting formula into its slot, and encode it.

3. Turn on auto-mode. Mortar and pestle is placed into output slot.  It is still reusable, but requires a recursive pipe connection to automate production of flour.

**Forge: 1.12.2-14.23.3.2655 
**Mekanism: 1.12.2-9.4.8.343
**Pam's+HarvestCraft+1.12.2t

**Comment by thiakil** [comment]
Definitely seems like something that could stay there in auto mode
