### ISSUE TITLE
Suggestion: Coal gasification to produce hydrogen gas and sulfur

### ISSUE THREAD

**Issue by WrongWeekend** [mekanism-mod/Mekanism#5054]
It would be useful to add a recipe in the PRC or another machine that allows for combining coal or charcoal with oxygen and water, steam, and/or water vapor to produce hydrogen gas and sulfur. This process is used in the real world and would be an effective way to use excess oxygen and coal to produce hydrogen for energy generation rather than just energy storage in the form of a gas.

**Comment by ToMe25** [comment]
I am implementing this and #5253.

**Comment by pupnewfster** [comment]
Version [9.8.0](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2746197) was just released and should sync to the twitch client within the next couple hours. It ended up being added as another "mode" rather than a hotkey.
