### ISSUE TITLE
Cardboard box wipes metadata

### ISSUE THREAD

**Issue by wraithlet** [mekanism-mod/Mekanism#5072]
#### Issue type:

- :bug: Bug

____

#### Short description:

When moving the Colossal Chest core (any variant of core) using the "Cardboard Box" from Mekanism, the contents of the core are wiped. Additionally, when the box is used on any CC block, it will iterate through multiple materials each time the box is added and removed from the colossal block.

#### Steps to reproduce the problem:

1. Use Colossal Chests 1.6.11 and Mekanism 9.4.10.345 (part of the ATM3 pack version 5.9.5)
2. Create Colossal Chest, any type.
3. Add contents into chest.
4. Attempt to move chest core using Mekanism box by applying box to core.
5. Place box at new location and remove box from core.
6. Observe material changed and inventory of core is now wiped.

#### Expected behaviour:

Block should retain metadata and inventory. Cross-posting to both mods sites due to interaction not clear which mod is failing to retain metadata properly.
____

#### Versions:

- This mod: Colossal Chests 1.6.11, Mekanism 9.4.10.345
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2678

#### Log file:

NA, no crash

**Comment by thiakil** [comment]
Moving multiblocks is generally not supported, should probably be added to the blacklist
