### ISSUE TITLE
Lapis Armour does not repair

### ISSUE THREAD

**Issue by yepidoodles** [mekanism-mod/Mekanism#5076]
#### Issue description:

When repairing Lapis Armour, it says it can be repaired, however it does not actually repair it. It will also take the xp and lapis without repairing it if you attempt to.
[![Screenshot from Gyazo](https://gyazo.com/db220a6d2b62929142d7e7f772e21e29/raw)](https://gyazo.com/db220a6d2b62929142d7e7f772e21e29)

#### Steps to reproduce:
1. Put lapis armour into anvil and add lapis

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2707
**Mekanism:** 9.4.10.345

#### If a (crash)log is relevant for this issue, link it here:
I don't think any logs are relevant, however I will provide one on request.

**Comment by thiakil** [comment]
![2019-03-24_20 38 08](https://user-images.githubusercontent.com/1788847/54879534-d77d5980-4e74-11e9-99b6-a47fee4b2fe9.png)

Can't reproduce it
