### ISSUE TITLE
[Suggestion]: Support for "Mystical Agriculture" / "Mystical Agradditions" ores

### ISSUE THREAD

**Issue by PearlCanopus** [mekanism-mod/Mekanism#5083]
I suggest to implement a compatibility for "Mystical Agriculture" / "Mystical Agradditions" ores.
I mine Prosperity- and Inferium-Ore with silk touch. Right now I cannot process these ores with Pulverizer or Enrichment Chamber or Crusher.

I'd like to see that in a future release, as far as these ores are registered well in OreDict.

**Comment by thiakil** [comment]
In the meantime it can be added by crafttweaker

**Comment by ToMe25** [comment]
I am Starting to implement this and a little bit more compat now.
