### ISSUE TITLE
do not emit a huge amount of particle when mutliblocks are formed

### ISSUE THREAD

**Issue by Xiaminou** [mekanism-mod/Mekanism#5085]
#### Issue description:
Every time I teleport near my Turbine it emits a lot of particles as if it were reforming (again) and lags my FPS down to 1 for 10 seconds.
I don't know what's causing this massive amount of lag but it needs to be fixed.

#### Version (make sure you are on the latest version before reporting):
**Minecraft:** 1.12.2
**Forge:** 2705
**Mekanism:** 9.4.11.346
**Other relevant version:** [list-alphabetical.txt](https://github.com/aidancbrady/Mekanism/files/2098298/list-alphabetical.txt)

**Comment by ruifung** [comment]
IMO, while it's initially formed is fine, but the emission of particles really should be suppressed while it's loaded.
