### ISSUE TITLE
Suggestion: A way of Measuring Induction Matrix's power

### ISSUE THREAD

**Issue by konradBalcerzak** [mekanism-mod/Mekanism#5099]
I love the Induction Matrix. It is customizable and scalable. My only problem with this thing is that it is really hard to measure the level of power inside. Comparators don't work on any block, Phantomfaces from Actually Additions break at higher power capacities and RFtools screens display only the Induction Port's energy storage. Adding something like a block that can output redstone like a comparator would be great for automation.

**Comment by Jorval** [comment]
i also have the same problem. a matrixcontroller would be fine or a data port.
i like to switch my reactor on and off by thresholds.
a port where we could read the amount of RF in the matrix could be enough and we can use redstone or rftools rf monitor for automation. a controller that outputs a redstone signal by thresholds would be perfect.
