### ISSUE TITLE
Quantum Entangloporter cannot be extracted from.

### ISSUE THREAD

**Issue by ruifung** [mekanism-mod/Mekanism#5100]
#### Issue description:
The quantum entangloporter does not seem to be able to be extracted from using mechanical pipes. This results in the fluid transfer rate being limited to its auto output rate, which is a paltry 256mB/t.

I remember some old issue here where it was said the auto eject rate is only 256mB/t and transmitters should be used to extract, but here mechanical pipes in pull mode aren't extracting anything.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.4.2705
**Mekanism: 9.4.13.349
**Other relevant version:**

**Comment by RhysWhy** [comment]
I am also running into this issue, multiplayer server, mechanical pipes set to pull mode. Nothing comes through. Set to normal mode it trickles through very slowly.

**Comment by TCloudGaming** [comment]
I've run into this too. Did some testing and it appears to be with the quantum entangloporter itself.

**Comment by thiakil** [comment]
In theory it should be able to extract the same as an Ultimate tier Mechanical Pipe (that's how much each frequency should be able to store), if it indeed got filled previously

**Comment by thiakil** [comment]
![2019-03-24_20 45 38](https://user-images.githubusercontent.com/1788847/54879609-e284b980-4e75-11e9-828b-e1efddefee06.png)

Works fine for me. Please ensure your Entangloporter is configured for output on that side
