### ISSUE TITLE
Request: Replace the osmium ingot in osmium compressor recipes with CraftTweaker

### ISSUE THREAD

**Issue by TheDeviantCrafter** [mekanism-mod/Mekanism#5103]
It sounds odd, but I'd like to make the osmium compresser use tin. In my pack I've put a lot of effort into limiting the pack to five metals: iron, gold, copper, tin and nickel. I've replaced almost a hundred recipes to accomplish this.

In my quest to cut down on clutter, I'd like to replace osmium with tin. I'd like to make the osmium compressor use tin, and rename it to the tin compresser. Unfortunately that doesn't seem to be possible.

**Comment by thiakil** [comment]
The CT handler does accept gas inputs, but the machine itself might not support turning that into gas, I can't remember

**Comment by tgstyle** [comment]
The only thing it supports is turning Osmium into a gas internally.
https://github.com/aidancbrady/Mekanism/blob/3e469fb40a2a086527cf14dbe9ba709f708a9bca/src/main/java/mekanism/common/tile/TileEntityOsmiumCompressor.java

**Comment by thiakil** [comment]
This should have been resolved in the 9.7 update
