### ISSUE TITLE
Duplicate Language key with some mods

### ISSUE THREAD

**Issue by TartaricAcid** [mekanism-mod/Mekanism#5111]
`gui.delete`
- customnpcs `Are you sure you want to delete this?`
- mekanism `Delete`

`gui.volume`
in other language there are different words
- extraambiance `Volume` <- sound
- mekanism `Volume` <- cubage

`gui.active`
- ftblib `Active`
- mekanism `Water-Cooled`

https://github.com/LatvianModder/FTBUtilities/issues/815
> **LatvianModder:** 
> wtf mekanism.. I think you should report this to them to change it to something like gui.water_cooled, because how the heck gui.active == Water-Cooled lol.

**Comment by thiakil** [comment]
> mekanism Water-Cooled
O_o

**Comment by thiakil** [comment]
Merging with #4698
