### ISSUE TITLE
Illegal Async Chunk Load crash

### ISSUE THREAD

**Issue by fcpwiz** [mekanism-mod/Mekanism#5113]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server crashes and produces following in console before crashing: https://gist.github.com/fcpwiz/4afbd26872a02810fd26eb7ebab7aeea

Chunks can't be loaded off of the main thread.

#### Version (make sure you are on the latest version before reporting):
Forge: 2705 (1.12.2)
Mekanism: 1.12.2-9.4.13.349
Other relevant version: SpongeForge: 2705-7.1.0-BETA-3235

**Comment by thiakil** [comment]
That method is guarded by a block that check if the chunk is loaded by 
```
if(tileEntity.getWorld().getChunkProvider().getLoadedChunk(x >> 4, z >> 4) == null)
{
	continue;
}
```

If its unloading in that time there is nothing we can do, and if sponge is screwing with that not being null, that's their problem.

**Comment by thiakil** [comment]
Checks around this code point were changed slightly recently. Please re-test on a recent release and comment if it still happens

**Comment by ChipWolf** [comment]
Exactly the same crash on MEKANISM-1.12.2-9.8.3.390 + Forge 14.23.5.2847 @thiakil 
Line 68 for us ` mekanism.common.content.miner.ThreadMinerSearch.run(ThreadMinerSearch.java:68)`

**Comment by tuxnull** [comment]
@thiakil 
Same crash, but Line 63. Version 1.12.2-9.8.3.390 
`mekanism.common.content.miner.ThreadMinerSearch.run(ThreadMinerSearch.java:63)`
