### ISSUE TITLE
Please add DUMP buttin in chemical crystalyse input gas.

### ISSUE THREAD

**Issue by prokopiy** [mekanism-mod/Mekanism#5121]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Please add DUMP button in chemical crystalyser input gas.
because the residual gas is blocking his work.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** latest
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by kkjdroid** [comment]
You can use the Gauge Dropper to remove gases or fluids from any machine. With the Chemical Crystallizer, it will only block if there's less than 200mB remaining, so just take the dropper, right-click on the gauge in the crystallizer's GUI, and then shift-right-click the air to empty the dropper.

**Comment by abytesmaller** [comment]
Using the Gauge Dropper, you can clear any liquid or gas from any machine by shift-left-clicking the tank (inside the gui). This will clear any remaining liquid or gas from said machine and allow you to use it with different liquids or gases.

**Comment by ruifung** [comment]
the problem with the gauge dropper is that it's horribly tedious to use.
Honestly, I wish there was a way to evenly split gasses. Heck, the funny thing is that it's called *slurry* and it's a gas. lol.
