### ISSUE TITLE
Support for Fashion TechGuns 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [mekanism-mod/Mekanism#5132]
Hello!
I enjoy your modification! This is the best I've seen!
I would like to make support for ore veins for TechGuns?
I wanted to smelt the mined ore into smelting, but it does not fit there :(
Thanks in advance!

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.4.2705-universal
**Mekanism:** Mekanism-1.12.2-9.4.13.349
**Other relevant version:** 1.12.2

**Comment by thiakil** [comment]
What kind of support are you after? Processing the mined blocks? Atomic disassembler?
How are they processed in the mod itself by default?

**Comment by xxxLEOPARDxxx** [comment]
Perhaps the interpreter did not translate correctly ...
The ore from the TechGuns mod is not melted down in the smelter from your fashion.
