### ISSUE TITLE
Salination Tower Heating

### ISSUE THREAD

**Issue by Moebius777** [mekanism-mod/Mekanism#5139]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am Trying to get more heat in the Tower. Using Solar panels and Placed in a Desert. For Some reason i cant conect heat pipes to the Valve / Fuelwood Heater and Resistive Heater both dont seem to work.
im new to the pack and couldent find any fix for this.

#### Steps to reproduce:
1. Grab any mecanism heater and try to connect it to a salination tower.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
1.12.2
**Mekanism:** 
1.12.2
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
screenshots please.

**Comment by Moebius777** [comment]
![c576cf6bf11edc13335b5f05122edea3](https://user-images.githubusercontent.com/42297017/44313401-78e88c80-a408-11e8-973e-1ad0b6222ebf.png)
![e4cfce4823e1e65e97946b1e8e8a5958](https://user-images.githubusercontent.com/42297017/44313408-8736a880-a408-11e8-9752-f4b4fb3b12ac.png
Keeps switching fast between Having a bit of water and no Fluid.

**Comment by themechman** [comment]
Remove solar panels from salination plant if you are going to use external heat source. You may have one or the other, but not both. This is a common error...

From your screenshot, your pump may not be pumping fast enough. Upgrades!

After using heat pipes, I find they are really only good for 6-8 blocks before they become pointless. You are better off putting your resistive heater right next to the valve. Resistive heaters MUST be powered to the green square sides. **_The green square side does not output heat!_**

Fuelwood heaters must be placed directly on valve. Orientation is of no importance.

**Comment by thiakil** [comment]
> Fuelwood heaters must be placed directly on valve

I am 99% sure that is not true.

@Moebius777 if you want help with the heat situation you need to show the heat connections as screenshots. Pump is likely not enough power / not enough upgrades.
