### ISSUE TITLE
Minecraft 1.12.2 crash with Mekanism

### ISSUE THREAD

**Issue by GmanAtheist** [mekanism-mod/Mekanism#5141]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Minecraftt 1.12.2 crash at startup and sometimes go to game and then after a few minutes crash with Mekanism as cause. Crashes with and without Optifine. 
Please help. Thanks.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** in image bellow 
**Mekanism:** Mekanism-1.12.2-9.4.13.349
** CoFHCore-1.12.2-4.5.3.20-universal
**Other relevant version:** 

Java 1.8.0.171.64

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
https://paste.dimdev.org/emuciginop.mccrash

![snag-0007](https://user-images.githubusercontent.com/5624207/44240385-b5707a00-a1b5-11e8-82c4-252c7ccec7bd.jpg)

**Comment by iKEVAREZ** [comment]
Try to downgrade java:
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-128302

**Comment by iKEVAREZ** [comment]
Try with Java 1.8.0 25

**Comment by thiakil** [comment]
looks like an issue with whatever cofh-based block you've connected the pipe to, its not crashing in our code.
