### ISSUE TITLE
Quantum Engangloporters do not respect allowProtection=false

### ISSUE THREAD

**Issue by TyanColte** [mekanism-mod/Mekanism#5156]
#### Issue description:
Changing allowProtection to false in the config on the server does not allow all players access to Quantum Engangloporters.

#### Steps to reproduce:
1. Change to allowProtection=false in mekanism.cfg
2. Reboot Server
3. Try to open somebody else's Quantum Entangloporter
4. No joy

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.4.2759
**Mekanism:** 9.4.13.349
**Other relevant version:** MC: 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No Crash
[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
How was the entangloporter configured?

**Comment by TyanColte** [comment]
Any more insight on this @thiakil ?

**Comment by thiakil** [comment]
I need to see how the Entangloporter is configured, with frequencies and such.

**Comment by TyanColte** [comment]
@thiakil I'm not sure what you mean. The Entangloporter just transports items, energy, and fluids based on the network you choose. However the issue i'm having is no matter how you have it set up in the config, only the person who placed the entangloporter can open it's GUI and configure it. I would like to set my server up to allow anyone who opens an entangloporter that anyone else has placed to be able to see it's gui. That currently doesn't seem possible.

**Comment by thiakil** [comment]
> and fluids based on the network you choose

That's exactly what I want to see, how hard is that to understand?
