### ISSUE TITLE
[1.12] Transport Pipes not running validation checks

### ISSUE THREAD

**Issue by DarkGuardsman** [mekanism-mod/Mekanism#5162]
#### Issue description:
Transport pipes are not running any item validation check when working with IItemHandler capabilities. This causes inventories which expect validation to be run to have items in invalid slots. 

https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/content/transporter/TransporterManager.java#L322

Javadoc for isItemValid, which should be run before doing an insert call.
![screenshot 2018-09-19 10 37 17](https://user-images.githubusercontent.com/1477330/45760495-34633300-bbf8-11e8-85fd-fb289bdbbebf.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.4.2759 
**Mekanism:** 1.12.2-9.4.13.349

**Comment by thiakil** [comment]
This is a new function which did not previously exist.

**Comment by DarkGuardsman** [comment]
Ya that is what I was thinking as well. I recall previously there was some extract or getSlot functionality that did this behavior as a filter check. Regardless it would be cool if you could fix it as it will become more common for mods to use the method.

**Comment by DarkGuardsman** [comment]
Just checking in, have you had a chance to work on this? If not care if I Pull Request the changes myself?

**Comment by thiakil** [comment]
@DarkGuardsman Reading over the javadoc, I'm not sure of the necessity of this.

The line you linked ([permalink](https://github.com/mekanism-mod/Mekanism/blob/5dd3dbb8a994d806d71038bb8707c5ea772c0e3e/src/main/java/mekanism/common/content/transporter/TransporterManager.java#L322)) is a simulation. If a provider returns an empty stack, it accepted the item. IMO its a flaw in the receiver if it does not check an inserted item is 'valid' in terms of filters etc

**Comment by DarkGuardsman** [comment]
Yes I read the docs that is why I posted this issue. Here are screenshots from the latest forge.

![image](https://user-images.githubusercontent.com/1477330/54868884-cb57a600-4d67-11e9-8d30-036e9f2ec296.png)
![image](https://user-images.githubusercontent.com/1477330/54868892-d7436800-4d67-11e9-958f-124acbb670c6.png)


Problem is a lot of mods do not validate on insert. As it is expected that a mod calls isItemValid before calling insert. This results in mekanism forcing items into slots on a few mods that have not implemented isItemValid internally.
