### ISSUE TITLE
API classes have reference to main mod

### ISSUE THREAD

**Issue by DaedalusGame** [mekanism-mod/Mekanism#5166]
mekanism.api.gas.Gas - references mekanism.client
mekanism.api.Coord4D - references mekanism.common
mekanism.api.transmitters.TransmitterNetworkRegistry - references mekanism.common

**Comment by thiakil** [comment]
Suboptimal, sure. But what is your exact issue with this?

**Comment by DaedalusGame** [comment]
because when i drop the api package into src/api/* without Mekanism in dev I'll get compile errors for non-existant classes.

**Comment by thiakil** [comment]
That's not how you're supposed to be using the api. Use the API jar.
