### ISSUE TITLE
[1.10.2] Energy cable crashes server and brakes the map

### ISSUE THREAD

**Issue by pcking99** [mekanism-mod/Mekanism#5180]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
We are using basic energy cables on some mods like Mekfarm, EnderIO, ExtremeReactors and Applied Energistics 2.
After a while of gaming it randomly crashes and brakes the map.
#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.10.2-12.18.3.2511-universal
**Mekanism:** Mekanism-1.10.2-9.2.4.103
**Other relevant version:** appliedenergistics2-rv4-stable-1, EnderIO-1.10.2-3.1.193, mekfarm-1.10.2-0.7.3 and ExtremeReactors-1.10.2-0.4.5.30

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/8Qk9qUcZ (Crash log)
https://www.dropbox.com/s/jflptnbcfsqmp9m/fml-server-latest.log?dl=0 (FML log)
[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
That's not an error that should happen (and would not happen randomly), something is broken in your mod setup
