### ISSUE TITLE
Rotary Condensentrator ignores NuclearCraft fluids

### ISSUE THREAD

**Issue by Ithronyar** [mekanism-mod/Mekanism#5233]
#### Issue description:
Not sure if this is a fluid registry problem or a specific mod compatibility problem, but since the problem is with a Mekanism machine I'll just post it here.

The Rotary Condensentrator doesn't convert NuclearCraft's fluids into their respective Mekanism gases. This applies to hydrogen, oxygen, sulfur dioxide, sulfur trioxide, and all their other shared fluids.

Advanced Rocketry seems to use them just fine, but I don't know if that's because it's specifically supported or there's some sort of Forge fluid registry that it uses.

Ideally the Condensentrator would detect and process any fluids with a corresponding Mekanism gas.

For example, anything registered/named "Hydrogen", "Liquid Hydrogen", "Hydrogen Fluid", etc. would convert into Mekanism's hydrogen gas. When converting it back to liquid, it would output whatever form of hydrogen is in the Condensentrator's internal tank. Otherwise it just outputs the normal Mekanism hydrogen.

#### Steps to reproduce:
1. Get a bucket/tank/whatever filled with NuclearCraft's hydrogen/oxygen/etc. Anything that Mekanism also uses.
2. Place in Rotary Condensentrator's fluid input slot. It should fill up the Condensentrator's internal buffer.
3. Nothing happens.

#### Version:
**Forge:** 14.23.5.2768
**Mekanism:** 9.4.13.349
**Other relevant version:** NuclearCraft v2.12h

**Comment by thiakil** [comment]
That's not really how it works (by default).

It is possible for those mods (or CraftTweaker with MTLib) to add recipes for it, _but_ it would interfere with some of the built ins, e.g. Oxygen (Mek gas) and Liquid Oxygen (Mek Fluid) are different.

Galacticraft (and possibly Advanced Rocketry) is coded specifically to support Mek Oxygen Gas.
