### ISSUE TITLE
Mekamosm BUG

### ISSUE THREAD

**Issue by coder-carl** [mekanism-mod/Mekanism#5257]
[crash-2019-01-21_08.55.53-server.txt](https://github.com/aidancbrady/Mekanism/files/2777733/crash-2019-01-21_08.55.53-server.txt)

**Comment by thiakil** [comment]
Need to know some more context here, it seems as though you moved the chest to a different slot while it was open, or changed your active hotbar slot

**Comment by thiakil** [comment]
merging with #5135
