### ISSUE TITLE
[config enhancement] Allow generators to have energy storage buffer changed

### ISSUE THREAD

**Issue by DemonfangArun** [mekanism-mod/Mekanism#5263]
Self explanatory title. In my modpack, generators do not have an energy buffer beyond what is required for them to output power, so you have to create proper energy storage (such as energy cubes). I would like to request that a config option for energy storage inside of the generators be added.

**Comment by DemonfangArun** [comment]
Bump

**Comment by DarkGuardsman** [comment]
Should be easy to add, I might look at this for the weekend. Though I've personally found the energy upgrades to work rather well.
