### ISSUE TITLE
Voice Server Sound Issues

### ISSUE THREAD

**Issue by loger42** [mekanism-mod/Mekanism#5264]
#### Issue description:
Mekanism Voice Server is causing all sounds (even windows system sounds) to stop playing when a recording device is connected and enabled. This only occurs when loading into a world however, and is immediately fixed upon exiting to the main menu of minecraft

disabling or disconnecting recording devices fixes the problem of system and other application sounds not working, but in-game sounds still do not work even with no recording devices.

disabling voice server fixes all these issues as well, and in-game sounds work with it disabled.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2808 (MC 1.12.2)
**Mekanism:** 9.4.13.349

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

log with Voice Server Enabled:  https://pastebin.com/8PE7kbRX

log with Voice Server Disabled:  https://pastebin.com/ZGxAL4Qg

**Comment by thiakil** [comment]
Will look into it. Though as far as I know the voice component hasn't had much attention post 1.7.10, given its not common;y used.

**Comment by thiakil** [comment]
As far as I can tell this may be an issue related to your audio drivers. The voice server opens the recording device on connection ready for use, but doesn't record until you press the button (I'm pretty sure anyway)

If you're running single player, the voice component is obviously not necessary unless you use the open to lan option and walkie-talkies

**Comment by loger42** [comment]
Interesting. It might be worth considering to have the voice server disabled by default, as Bluetooth recording devices often cause problems like this. I figured out later that this was the case for me.

**Comment by thiakil** [comment]
Yeah I have some ideas around ways we can mitigate this a little
