### ISSUE TITLE
FEATURE: Allow fuel injection rate to be controlled with redstone or a computer mod like OpenComputers

### ISSUE THREAD

**Issue by 23Link89** [mekanism-mod/Mekanism#5265]
This was something you hinted at wayyy back in 2015 with #2412. I'd absolutely love to be able to have an OpenComputers program manage my reactors when fuel gets low or automatically restart them if they shut off. 

The only thing I am able to really do is monitor fuel levels from external tanks and inject D-T Fuel when power storage is low.

**Comment by thiakil** [comment]
there is a `setInjectionRate` command and some others that should be available to OC (via an Adapter I would imagine)

What exactly is missing?

**Comment by 23Link89** [comment]
It might be that I'm 1.10.2, but there's no block that will connect to any OC cable I give it. If it is an MC version thing, could you backport it to 1.10.2?

**Comment by thiakil** [comment]
Have you tried with an Adapter? Not sure if that's what you meant you'd tried by 'any OC cable'

It should be in 1.10 yes
