### ISSUE TITLE
Sound keeps play after machine is broken

### ISSUE THREAD

**Issue by DarkGuardsman** [mekanism-mod/Mekanism#5277]
#### Issue description:
Broke 3 precision sawmills serverside while in creative mode. Audio continued to play until the client was restarted. Have been unable to reproduce consistently. Though it may be reproduced on other machines. Few other users reported similar issues both in single player and server side.

Modpack we are using is M12 Voltz modpack. The pack contains little to no mods that should interact with audio. See related files on pack for list. https://minecraft.curseforge.com/projects/volts-m12/files/2671113

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2811
**Mekanism:** Mekanism 1.12.2-0.4.13.349

**Comment by thiakil** [comment]
the latest sound changes *should* resolve this, but reply if they don't and will re-open

**Comment by DarkGuardsman** [comment]
Will see if I can test it this weekend, good work
