### ISSUE TITLE
Universial Cables not connecting with IC2 machine

### ISSUE THREAD

**Issue by fabrossmann** [mekanism-mod/Mekanism#5280]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

After unloading the world, the cables disconnect from ic2 machines, when using them. To connect them you have to restart the server.

#### Steps to reproduce:
1. Unload World
2. Use IC2 Machine
3. Connection is away

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2796** 
**Mekanism:9.4.13.349** 
**Other relevant version: IC2: 2.8.109-ex112** 
**Modpack: Enigmatica2: 1.54**

![2019-02-15_17 43 39](https://user-images.githubusercontent.com/6189957/52871131-a5782980-3149-11e9-970c-0a031198f50d.png)

**Comment by thiakil** [comment]
Unfortunately I can't reproduce this, could you provide a server log?
