### ISSUE TITLE
PrefilledFluidTanks and PrefilledPortableTanks not showing up in config

### ISSUE THREAD

**Issue by Vortex67** [mekanism-mod/Mekanism#5281]
Trying to actually see them (opposite of what most issues related to this are) but for some reason the config just isn't there. PrefilledGasTanks is however and enabling that shows the gas fine.
**Forge:** 14.23.5.2808
**Mekanism:** Latest

**Edit**: Adding the options manually in the config seems to be registered in Mod Options ingame, but it doesnt actually change anything

**Comment by thiakil** [comment]
There is indeed no option to add prefilled tanks of liquid (possibly related to the portable tank being on the same item as other machines)

> Edit: Adding the options manually in the config seems to be registered in Mod Options ingame, but it doesnt actually change anything

Yeah it's based on forge's system which will show whatever config options it reads from the file.
