### ISSUE TITLE
Blocks that should produce lighting

### ISSUE THREAD

**Issue by Redd56** [mekanism-mod/Mekanism#5301]
This is an  
A S T H E T I C
sugestion. Simply put many of the blocks i would think would have a light value of something, but have no light value. In particular all the universial cables which imo should be probably like 5 or 7 with shader color set to green, dark green. Things like the compressed glowstone block dont have fynamic lights. And even liquid tubes when glowing liquid is in them, ill kake a better list when i get home but for now this is it. (At work on phone cant be assed tk correct spelling :p)

**Comment by Redd56** [comment]
Btw if i was told how i could help with it

**Comment by Redd56** [comment]
Gonna throw some notes here as i work if i think of random stuff:
Reactor. Change brightness based on injection rate not dynamic, 

Atomic diss: blue dynamic only

Glowstone: dynamic lighting support as it dont have it

**Comment by thiakil** [comment]
the main part is at `mekanism.common.block.BlockMachine#getLightValue` - but doing block light updates like this is horrid with MC because it redraws the whole chunk iirc.

So one of the dynamic lighting systems like albedo could be usable

**Comment by Redd56** [comment]
I meant for optifine dynamic lighting, cause for some reason it dont see it as a light source. Which is odd

**Comment by thiakil** [comment]
ah, right I may have misunderstood your initial post. I had somehow thought you meant the existing functionality of machines that produce light like torches do.

**Comment by Redd56** [comment]
Kinda, for the pipes yes, but it would be configurable to turn off as it would cause alot of strain on servers if someone abused it or barely didnt have enough gens to power their stuff. But for things like torcges in logistical trnasporters, that eould be on optifines side, and the green pulsing of the cables would be shader supported stuff

**Comment by thiakil** [comment]
Is there any specific information I can help with?

**Comment by Redd56** [comment]
Just an example of how i would do it. Mainly for the logistical transporters or mechanicalnpipes, i can probably figure out the universial cable on my own

**Comment by Redd56** [comment]
After i see one fluid i can copy it over for like a million other mods, unless we can make a configu system to register fluids and items at launch that have light dynamic or static

**Comment by thiakil** [comment]
most of that stuff would be handled by the renderer classes. e.g. `mekanism.client.render.transmitter.RenderLogisticalTransporter`

I wouldn't be adding any new stuff for block light (i.e the server side concept which prevents mob spawning) due to the hefty re-render costs

**Comment by Redd56** [comment]
true... but machines do allow it if you enable it in the config, maybe it could be like that?

**Comment by thiakil** [comment]
it could be but I intend to move away from that being block light to being just rendered like that

**Comment by Redd56** [comment]
good idea... that way the server isnt strained, good idea.

**Comment by thiakil** [comment]
well, its more of a client issue. Light updates cause the whole chunk to re-render (its otherwise cached), killing performance

**Comment by Redd56** [comment]
O, didnt know that, also only the static light of the reactor and the either on or off of the cable would work without optifine, other fancy things like items and liquids would be optifine dynamic lights exclusive. Even then the lightweight stuff would even be configurable to be able to be dissabled client side

**Comment by Redd56** [comment]
Unless thats a bad idea

**Comment by thiakil** [comment]
Optifine tends to leave a bad taste in the mouth. You could alternatively use https://minecraft.curseforge.com/projects/albedo

Or of course code it to be able to work with both
