### ISSUE TITLE
[1.12.2]Mekanism chunkloading everything regardless of forgechunkloading configs

### ISSUE THREAD

**Issue by CraftalotReloaded** [mekanism-mod/Mekanism#5304]
Mekanism chunkloads every single chunk it is in at all time causing horrible performance no matter what the forgechunkloading configs are

Forge: 14.23.5.2811
Mekanism: 1.12.2-9.6.3.355(and many older versions had the same issue)

**Comment by thiakil** [comment]
Could you please provide your evidence of this? I can assure you it doesn't explicitly do it and the Anchor Upgrade itself uses Forge's chunkloading system

**Comment by CraftalotReloaded** [comment]
I'll get your evidence if i can later, but the server does spam this literally like a thousand times on startup
[06:29:27] [Server thread/FATAL] [FML]: The mod mekanism attempted to force load a chunk with an invalid ticket. This is not permitted.

That's with version 353 though but imma say it anyways incase you didn't fix that yet

**Comment by thiakil** [comment]
That message has been fixed, but in fact has the opposite effect to your claim, it means the chunks weren't reloaded on startup for those that had anchor upgrades

**Comment by CraftalotReloaded** [comment]
We do not have like a thousand anchor upgrades at all, it is just a small private test server xD

**Comment by thiakil** [comment]
Please update to the latest Mekanism release and send me your `forcedchunks.dat` files (note that there may be one for each dimension).

It's impossible to say what *might* be causing it - it may not even be Mekanism.

**Comment by thiakil** [comment]
Was discussed outside of Github, nothing explicitly Mekanism was found
