### ISSUE TITLE
[1.12.2]Poor logistical transporter behaviour

### ISSUE THREAD

**Issue by CraftalotReloaded** [mekanism-mod/Mekanism#5305]
If you for example have a bin that constantly loses 1 item at a time with more bins next to it connected through logistical pipes, no matter how good the pipes are, it will keep on adding 1 item at a time to the first bin to fill it up again and will never start filling the other bins.

If its behaviour was good enough it would send as much as it could, fill up the first bin again and send the rest to the next bin

Forge: 14.23.5.2811
Mekanism: 1.12.2-9.6.3.355(and many older versions had the same issue)

**Comment by thiakil** [comment]
Have you tried the Logistical Sorter's round robin mode?

**Comment by CraftalotReloaded** [comment]
No, but imo you shouldn't need the sorter for something simple as this

**Comment by thiakil** [comment]
Can you do me up a minimal reproduction setup?

**Comment by CraftalotReloaded** [comment]
Interesting, seems like they behave properly now lol
