### ISSUE TITLE
[1.12.2]TPS and FPS lagspike upon multiblock completion

### ISSUE THREAD

**Issue by CraftalotReloaded** [mekanism-mod/Mekanism#5307]
Upon completing any multiblock it causes far more tps and fps lag than it should.

Forge: 14.23.5.2811
Mekanism: 1.12.2-9.6.3.355(and many older versions had the same issue)

**Comment by thiakil** [comment]
FPS is likely to do with the particles, as for tps lag, profiling evidence would be appreciated

**Comment by DarkGuardsman** [comment]
I've experienced this as well, maybe we could add a config to disable particle effect just to see if it is the cause. I doubt it is the only reason but would need to look at the code.
