### ISSUE TITLE
Gas tanks/tanks/bins, etc default to wrong values

### ISSUE THREAD

**Issue by dizzyd** [mekanism-mod/Mekanism#5313]
With the latest build of Mekanism, a basic tank now holds 14k units instead of the expected 64k. It looks like similar problems occur with bins, tanks, etc.

**Comment by thiakil** [comment]
Damn. If you spot any more wrong defaults [here](https://github.com/mekanism-mod/Mekanism/blob/1.12/src/main/java/mekanism/common/config/TierConfig.java#L46) please let me know
