### ISSUE TITLE
Recipes not shown in JEI

### ISSUE THREAD

**Issue by Manuepolis23** [mekanism-mod/Mekanism#5314]
#### Issue description:
In the last release the osmium compressor recipes are not shown in the JEI but they are working in the machine.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2784
**Mekanism: 1.12.2-9.6.5.357
**JEI: 1.12.2-4.15.0.269

**Comment by HurtsAsHell** [comment]
Same for me
