### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity with universal cables

### ISSUE THREAD

**Issue by CausticLasagne** [mekanism-mod/Mekanism#5315]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
This issue has happened twice.
Teleported from Overworld to Spectre Dimension -> Game Crashed
Game Restarted
Teleported from Spectre Dimension to Overworld -> Game Crashed
#### Steps to reproduce:
1. Make RFTools Reciever, Sender and Dialer
2. Connect to power source using Mekanism Universal cable
3. Repeat above in spectre dimension
4. Teleport between dimensions

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2511
**Mekanism:** MEKANISMGENERATORS-1.10.2-9.2.4.103
**Mekanism:** MEKANISMTOOLS-1.10.2-9.2.4.103
**RFTOOLS** RFTOOLS-1.1X-7.16
**Other relevant version:** 
World type is creative custom superflat, crash may have been caused by server overload.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/q0MkuTB6

**Comment by thiakil** [comment]
#4374

Not us

**Comment by CausticLasagne** [comment]
I am not really into minecraft mods these days. Can you identify which mod(s) are causing the issue so I can forward it to the correct area please?

**Comment by thiakil** [comment]
There's a link in the issue I linked to McMultipart. It seems like it's a bug they never fixed.

The only solution may be to remove McMultipart from your mods

**Comment by CausticLasagne** [comment]
Okay thank you. Love your mod by the way. Have a nice day.

**Comment by CausticLasagne** [comment]
Apparently MCMultipart have fixed this in MCMultiPart-experimental-2.0.0_88-universal. If your mod is automatically download it could you make it acquire the fixed version. Thanks. Also love your mod and the universal cables are boss.
