### ISSUE TITLE
Location of Digital miner

### ISSUE THREAD

**Issue by dierke9** [mekanism-mod/Mekanism#5316]
For a project i'm currently working on i need the location of the digital miner on the moment it wants to mine a block (Trying to get it during the BlockEvent.BreakEvent)
The FakePlayerEntity uses the location of the block to mine, is there a way to get the location of the miner itself ?

**Comment by thiakil** [comment]
As far as I know the Miner doesnt fire `BlockEvent.BreakEvent`, it only fires the harvest drops one

**Comment by dierke9** [comment]
It does use that even. It fires it of itself to check if it isnt cancelled yet or not.
Class: TileEntityDigitalMiner
Method: canMine
Line: 406

**Comment by thiakil** [comment]
aha! right you are
