### ISSUE TITLE
[1.12.2] Mekanism + Simpleoregen crash

### ISSUE THREAD

**Issue by MetalBox47** [mekanism-mod/Mekanism#5317]
#### Issue description:
While using Mekanism and SimpleOreGen in the same modpack, simpleoregen just crashes the game saying that mekanism is missing a class.

#### Steps to reproduce:
1. Install Mekanism, JEI, and SimpleOreGen into a modpack
2. Run modpack
3. get crash

#### Versions:
**Forge:** 14.23.5.2821
**Mekanism:** 1.12.2-9.6.6.358
**Other relevant version:** 
- SimpleOreGen:  4.3.2
- JEI: 4.15.0.268

Crash Log:
https://pastebin.com/dxuVuZPE

**Comment by thiakil** [comment]
Report to SimpleOreGen, they shouldn't be using internal classes.
