### ISSUE TITLE
Undrainable Tanks

### ISSUE THREAD

**Issue by DemonfangArun** [mekanism-mod/Mekanism#5318]
Forge: 2811
Mekanism(main/generators/tools): 9.6.2.354

Fluids cannot be pulled out of a dynamic tank either via mekanism's own piping or via that from other mods (I tested with a barebones profile prior to this report, it's a mekanism issue). May be related to the prior unfillable tank issue.

**Comment by thiakil** [comment]
Please test with latest version.

**Comment by DemonfangArun** [comment]
I can't type, that was supposed to be an 8, not a 4 #longday
