### ISSUE TITLE
Error when updating world from 1.12.2-9.4.13.349 to 1.12.2-9.6.1.353 tile.turbine.TileEntityTurbineVent

### ISSUE THREAD

**Issue by evanleeturner** [mekanism-mod/Mekanism#5321]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Greetings,

Let me say I have been very excited by the recent activity in this codebase and all the code pulls being accomplished.  I decided to try to go ahead and update my server to the latest and greatest and see what occurs!  We have other mods running, and this server is stable in mekanism 1.12.2-9.4.13.349.  Now, the updated modpack works JUST FINE as a brand new world - but crashes when trying to load the server world.  (https://www.technicpack.net/modpack/build3rs-engineering-pack.1264622) Obviously, we want to be able to keep the world we have without too much hassle.   Is there any recommendations you could make? Do we just need to remove the offending blocks from the world and move on?

Here is our old existing technic modpack that works:
https://www.dropbox.com/s/olvsz072yrnvpal/ourmodpack-1.11.zip?dl=1
![image](https://user-images.githubusercontent.com/11633165/54851114-f7ffb500-4cb6-11e9-983e-f8479fbbbea1.png)
![image](https://user-images.githubusercontent.com/11633165/54851146-0bab1b80-4cb7-11e9-9b61-31a1d69e8798.png)

When I upload our server to use 1.12.2-9.6.1.353 we encounter the error when loading our world:  

java.lang.NullPointerException: Ticking block entity
	at mekanism.generators.common.tile.turbine.TileEntityTurbineVent.canDrain(TileEntityTurbineVent.java:92)
	at mekanism.common.base.FluidHandlerWrapper.drain(FluidHandlerWrapper.java:70)
	at mekanism.common.tile.transmitter.TileEntityMechanicalPipe.func_73660_a(TileEntityMechanicalPipe.java:70)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
[crash-2019-03-22_13.09.24-server.txt](https://github.com/mekanism-mod/Mekanism/files/2998192/crash-2019-03-22_13.09.24-server.txt)

I've attached the full crashlog to this issue.

 

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Could you please try with the latest release? (9.6.6.358)
Those null issues should have been fixed

**Comment by evanleeturner** [comment]
Will Do!  I was out this week and will try it today when I get home.  The reason why I used 9.6.1.353 was because it was the most recent release that was listed in the public download page.  

Again, want to thank you for making a great mod and for all the work put in by this group.  Very happy  to see this project continuing!

**Comment by evanleeturner** [comment]
Getting same issue with 1.12.2-9.6.7.360  That is the most current build listed on the download page.  Full crash report pasted to this...
[crash-2019-03-25_17.46.30-server.txt](https://github.com/mekanism-mod/Mekanism/files/3006029/crash-2019-03-25_17.46.30-server.txt)

**Comment by evanleeturner** [comment]
Same error in 9.6.6.359
[crash-2019-03-25_18.16.42-server.txt](https://github.com/mekanism-mod/Mekanism/files/3006085/crash-2019-03-25_18.16.42-server.txt)

**Comment by thiakil** [comment]
Well one issue down, now a new one appears.

This one's much simpler - your Forge version is a little too old! I'll need to update the requirement that Mekanism reports to forge.

To make it simpler, please update your Forge to the latest Recommended build on their download page.
