### ISSUE TITLE
Digital Miner Ore Dupe (works with just base mekanism)

### ISSUE THREAD

**Issue by kragnoth** [mekanism-mod/Mekanism#5324]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When you leave ore in the miner with a chest in the eject area, and then hit the eject button, it will eject as much ore as is in the miner (without ejecting it) of that type of ore into the chest.

I have 32 gold in the miner, hit auto eject, it now ejects 32 gold into the chest every time it mines one gold

#### Steps to reproduce:
1. Install mekanism
2. Mine ore
3. Hit eject
4. Ejects as much ore as is in machine

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.2 forge 14.23.5.2823
**Mekanism: mekanism-1.12.2-9.6.6.358
**Other relevant version: (I also have actually additions r146 installed so I can have a bigger chest to test with)

There are no crashes, just duped ore.  The log is literally just all loading log files as well, no errors on mining or placement of items/etc.

**Comment by thiakil** [comment]
Will look into it

Your attitude towards this on discord is atrocious btw.
