### ISSUE TITLE
Would a 1.13+ port be possible

### ISSUE THREAD

**Issue by term2112** [mekanism-mod/Mekanism#5326]
I am not sure if it is appropriate to ask this here and this is one of the first times using this website. My question would be weather or not a 1.13+ port is possible now that forge 1.13.2 has been released. I am not sure about the process of porting to a new version or whether several bugs would be created in the process. I would expect bugs on the electric pump due to the new water physics. Another question that I have would be weather the port or mekanism V10 would come out first.

**Comment by SacrificialFlame** [comment]
@term2112 I doubt they will update to 1.13 anytime soon as there is no recommend build out for 1.13+ forge

**Comment by thiakil** [comment]
It will definitely happen at *some* point, but as mentioned Forge for 1.13 is rather 'beta' at the moment, so it's not a high priority for me. Forge might not even get to a stable stage on 1.13 with 1.14 so close, it's hard to say.

That said, I wouldn't say no to anyone submitting a PR to get the bulk of the conversion done - that's basically how the 1.12 port went down back when Tom and I first got involved with Mek dev
