### ISSUE TITLE
Mekanica, a copy of mekanism ?

### ISSUE THREAD

**Issue by Nethet** [mekanism-mod/Mekanism#5330]
Hello you,

Yesterday I updated my little modpack and found a mod called Mekanica :
https://minecraft.curseforge.com/projects/mekanica
I asked me if the mekanism team know abou it, because it's mekanism but "optimized" as the author says.
Can I trust this mod ?
I know this isn't an issue but I don't know where I have to post it to be read.

Cordially,
Nethet

**Comment by ate0ate** [comment]
Its made by the same team now so you sure can trust it. Just look at the github or Discord for it. Aidan himself is there as well as Thiakil. Mekanica started as a fork of Mekanism with a slightly different focus on optimisation, but now the mods have merged and an official merged version of both mods is due out the 7th of April. Til then, Mekanica is technically the most up to date version of Mekanism and the only branch being actively developed, so I would recommend using that til the great merger takes place.

**Comment by thiakil** [comment]
Yeah it's a Fork, which is similar to a copy. As mentioned we've combined forces, but the big code merge hasn't happened, so the Mekanica devs are still working on their repo for the moment.

Trying to say one is more up to date than the other is a bit of a misnomer/oversimplification tbh. Both projects pulled in changes from the other.

If you aren't experiencing any major bugs, just stay on Mekanism, and when the merge/update happens you'll just need to bump the version.
