### ISSUE TITLE
Ethylene Not Outputting from PRC

### ISSUE THREAD

**Issue by NGSquirrely** [mekanism-mod/Mekanism#5331]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Build PRC with required inputs and output receptacle 
2. Run it
3. Minus Profit

#### Version (make sure you are on the latest version before reporting):
**Forge:** Latest
**Mekanism:** Latest
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by kohlth** [comment]
1.did you put output to auto output?

2.did you chnage the right config (gas instead of items or fluids or energy)?

3.is the output pulling? 

4. Is etheleyene being made?

**Comment by thiakil** [comment]
Can't reproduce in 1.12 branch, so if there is somehow an issue it will be resolved in the 9.7 release
