### ISSUE TITLE
Server crash because of thermal evaporation plant.

### ISSUE THREAD

**Issue by PyroGameur** [mekanism-mod/Mekanism#5334]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
A user of my server makes the server crash when he get on due to thermal evaporation plant.. 

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2823** 
**Mekanism: 9.6.7.360** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/rnQMu1SG

**Comment by GamyGamer** [comment]
It looks like crash (or better freeze) occur, when thermal base is going to build, I have the same problem but in single-player mode.

**Comment by pupnewfster** [comment]
Should be fixed in the newest 9.6 builds (I believe) but at the very least I believe it is fixed in the 9.7 update released today: https://minecraft.curseforge.com/projects/mekanism/files/2698323
