### ISSUE TITLE
Crash both client and server

### ISSUE THREAD

**Issue by lebanni** [mekanism-mod/Mekanism#5338]
Mekanism v9.6.8.365
forge-1.12.2-14.23.5.2824-universal.jar

Crash at start.
[crash-2019-04-04_09.43.28-server.txt](https://github.com/mekanism-mod/Mekanism/files/3042532/crash-2019-04-04_09.43.28-server.txt)
[crash-2019-04-04_09.43.22-client.txt](https://github.com/mekanism-mod/Mekanism/files/3042534/crash-2019-04-04_09.43.22-client.txt)

**Comment by thiakil** [comment]
Fixed in https://minecraft.curseforge.com/projects/mekanism/files/2695600
