### ISSUE TITLE
 Mekanism-1.12.2-9.6.8.365 - crash on startup

### ISSUE THREAD

**Issue by RedProjectZer0** [mekanism-mod/Mekanism#5340]
#### Issue description:
Mekanism crashs on startup, can you please give it a look? Thanks

`java.lang.ExceptionInInitializerError`
    at `mekanism.common.base.IFactory$RecipeType.<clinit>(IFactory.java:59)`

#### Version (make sure you are on the latest version before reporting):
Forge-1.12.2-14.23.5.2824
Mekanism-1.12.2-9.6.8.365

#### Crash log:
https://pastebin.com/XMqfKpxn

**Comment by zISKo666** [comment]
Having the same issue ... :sadfacepanda:

**Comment by GhEppIO82** [comment]
same issues with forge 2806 :( ciao

**Comment by jubalearly** [comment]
Tested in clean install with just Mek and both Forge 2824 and 2799, same crash.

**Comment by Darkfiend009** [comment]
Also experiencing this on 2824

**Comment by CritFlaw** [comment]
Same with 2808

**Comment by Chupp4-Jo3** [comment]
https://pastebin.com/z46pRF0E

YeMe2

**Comment by Secretname2009** [comment]
Im having the same issue, just downloaded this Version and this appeared.

**Comment by TheGoldenProof** [comment]
Same issue, 9.6.8.365, forge 2824. [crash report](https://pastebin.com/Y2LcAMC5). project ozone 3

**Comment by Trnrr** [comment]
Same issue, forge 2807

**Comment by AwesomeAnimationGamer** [comment]
Happening for me too, Forge 2824

**Comment by HurtsAsHell** [comment]
Same for me

**Comment by DaRcCrysys** [comment]
Same crash, after updating to 9.6.8.x (forge 2824), tried with clean install Mek and dependencies only, and in a full mod pack, (self created profile).

Same error on both packs, although to be fair I did only try with forge 2824.

**Comment by dizzyd** [comment]
Hi everyone - this appears to be a problem with the actual build. I've contact @aidancbrady and @thiakil to do a new build ASAP. In the meantime you have two options:
1. Revert to previous version
2. Do a build by hand from the repo branch 1.12_old. 

My apologies for the inconvenience; we'll get this fixed ASAP.

**Comment by heliomoreno** [comment]
Same issue, 9.6.8.365, forge 2768 [crash reporte](https://pastebin.com/5RUk0mee).

**Comment by thiakil** [comment]
fixed in https://minecraft.curseforge.com/projects/mekanism/files/2695600

**Comment by RedProjectZer0** [comment]
Thanks, it's works again.

**Comment by CritFlaw** [comment]
Ditto

**Comment by AwesomeAnimationGamer** [comment]
Working, thanks!
