### ISSUE TITLE
Unrecoverable crash after attempting Auto-Eject

### ISSUE THREAD

**Issue by lathanwc** [mekanism-mod/Mekanism#5344]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Turn on Auto-eject. game crashed.  now can't reload the game at all

#### Steps to reproduce:
1. Put hopper on top of Energized Smelter
2. Put chest on top of hopper
3.Load chest with different types of dust
4. Wait for a few of the dusts to turn into ignots.(in this case, copper)
5. Place chest to the right of Energized Smelter.  (NOte: This also ends up with the chest being to the left of a Metallurgic Infuser that I believe was producing steel dust)
6. Turn on Auto-Eject at Energized Smelter
7. After a few seconds, game crashes and cannot be recovered.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.4.2705
**Mekanism:** 1.12.2-9.6.7.360
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 4/4/19 9:24 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraftforge.items.IItemHandler.isItemValid(ILnet/minecraft/item/ItemStack;)Z
	at mekanism.common.util.InventoryUtils.putStackInInventory(InventoryUtils.java:91)
	at mekanism.common.tile.component.TileComponentEjector.outputItems(TileComponentEjector.java:212)
	at mekanism.common.tile.component.TileComponentEjector.tick(TileComponentEjector.java:105)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:87)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mekanism.common.util.InventoryUtils.putStackInInventory(InventoryUtils.java:91)
	at mekanism.common.tile.component.TileComponentEjector.outputItems(TileComponentEjector.java:212)
	at mekanism.common.tile.component.TileComponentEjector.tick(TileComponentEjector.java:105)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:87)

-- Block entity being ticked --
Details:
	Name: mekanism:energized_smelter // mekanism.common.tile.TileEntityEnergizedSmelter
	Block type: ID #256 (tile.MachineBlock // null)
	Block data value: 10 / 0xA / 0b1010
	Block location: World: (-51,38,-399), Chunk: (at 13,2,1 in -4,-25; contains blocks -64,0,-400 to -49,255,-385), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #256 (tile.MachineBlock // null)
	Actual block data value: 10 / 0xA / 0b1010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['LilStopey'/149, l='New World', x=-49.69, y=38.00, z=-397.32]]
	Chunk stats: ServerChunkCache: 755 Drop: 0
	Level seed: -2415288656021689837
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-168,64,-20), Chunk: (at 8,4,12 in -11,-2; contains blocks -176,0,-32 to -161,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 348558 game time, 348558 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 58819 (now: false), thunder time: 30163 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1008247368 bytes (961 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                 | Version                  | Source                                  | Signature                                |
	|:--------- |:------------------ |:------------------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft          | 1.12.2                   | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                | 9.42                     | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                | 8.0.99.99                | forge-1.12.2-14.23.4.2705.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge              | 14.23.4.2705             | forge-1.12.2-14.23.4.2705.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | inventorytweaks    | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jei                | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar               | None                                     |
	| UCHIJAAAA | journeymap         | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar             | None                                     |
	| UCHIJAAAA | mekanism           | 1.12.2-9.6.7.360         | Mekanism-1.12.2-9.6.7.360.jar           | None                                     |
	| UCHIJAAAA | mekanismgenerators | 1.12.2-9.6.7.360         | MekanismGenerators-1.12.2-9.6.7.360.jar | None                                     |
	| UCHIJAAAA | mekanismtools      | 1.12.2-9.6.7.360         | MekanismTools-1.12.2-9.6.7.360.jar      | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['LilStopey'/149, l='New World', x=-49.69, y=38.00, z=-397.32]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by thiakil** [comment]
Update your forge, it's too old.

Note to self/devs: forge required version check not working?

**Comment by thiakil** [comment]
Also please use a service like Pastebin/Gist for crashlogs in future

**Comment by hnOsmium0001** [comment]
Or use the collapse function in the editor.
