### ISSUE TITLE
Game freeze from thermal plant (might be related to bug report #5334)

### ISSUE THREAD

**Issue by GamyGamer** [mekanism-mod/Mekanism#5354]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game frezze when someone will place base of thermal plant (more detail in vid).
By frezze I mean Entities do not respond, Chunks won't load, can't acces to any interfaces, can't drop items ect. and when closing map/world game frezze totally (need to alt+f4) (There is no information from logs, not generated)

#### Steps to reproduce:
1.Place base thermal block (mekanism:basicblock2)
2.Done.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.2 - 14.23.5.2768** 
**Mekanism: 1.12.2-9.6.8.366** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://streamable.com/s0ll4

#### Addnotial info for vid
Firstly I placed interface, break it, and placed thermal block

**Comment by jubalearly** [comment]
Same issue Forge 2823.  My crashes are not creating logs as I have to end task.
