### ISSUE TITLE
Oredictionificator crashes 

### ISSUE THREAD

**Issue by leonekmi** [mekanism-mod/Mekanism#5363]
#### Issue description:

Oredictionificator make the game crashes when you put a IO cable in a non-supported face.

#### Steps to reproduce:
1. Place an Oredictionificator
2. Place a Logistical Cable on back for example
3. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2824 
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/KRaRjhmZ

**Comment by thiakil** [comment]
Update Mekanism, this was fixed
