### ISSUE TITLE
Rotary Condensentrator not working

### ISSUE THREAD

**Issue by RedFox70** [mekanism-mod/Mekanism#5377]
#### Issue description:
I can't pump out any fluids and I can't use buckets to take out the fluid either

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://paste.dimdev.org/ameqihukeh.mccrash

**Comment by thiakil** [comment]
Use the latest release, you're at least 8 versions behind

**Comment by RedFox70** [comment]
> Use the latest release, you're at least 8 versions behind

I can't change it I'm on a server

**Comment by thiakil** [comment]
Not sure how you expect us to help you then... You'll need to complain to your server admin, as I'm pretty sure fluid bugs were fixed
