### ISSUE TITLE
Crash Ticking block entity

### ISSUE THREAD

**Issue by TheRealDadbeard** [mekanism-mod/Mekanism#5388]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
This is on a server where other people play and after going to a certain location where many Mekanism machines are I'm getting a crash

#### Steps to reproduce:
Just crashing when going near this place. Stuck there now hmm :/ Logs will help

#### Version (make sure you are on the latest version before reporting):
**Forge:2795** 
**Mekanism:9.7.0.369** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://paste.dimdev.org/yocirugayi.mccrash

https://paste.dimdev.org/tebiviqewa.mccrash

**Comment by Trixz2018** [comment]
ive had this happen to me sometimes when switching worlds in SP. its the steam turbine causing the issue but cannot seem to reproduce it

**Comment by pupnewfster** [comment]
Don't have my IDE open right now but I believe it is because of it using the render location https://github.com/mekanism-mod/Mekanism/blob/1.12/src/main/java/mekanism/common/tile/TileEntityMultiblock.java#L82 which I will need to check *may* not exist on the server side.

**Comment by TheRealDadbeard** [comment]
after downgrading to the one before everything is fine

**Comment by Trixz2018** [comment]
ok i was able to reproduce it.  have a steam turbine and steam boiler setup and running, close out world and then try to reenter world ( at this point the game crashes).

**Comment by thiakil** [comment]
@Trixz2018 have you got that reproduction in a test word with just the turbine/boiler?

The turbine/boiler I have set up in my test environment don't seem to have this problem :|

**Comment by Trixz2018** [comment]
@thiakil  it wasnt in my test server, it was in my SP play world. Considering i kno nothing about java or modding in minecraft, would the multiblock being in different chunks cause this issue?

**Comment by thiakil** [comment]
It's certainly possible. I've added a check for the NullPointer, but without beng able to reproduce it, its uncertain whether it does what we want (past stopping a crash)

Btw, doesnt matterserver/client for the purposes of sending a save folder, as long as we know which is was for ;)

**Comment by Trixz2018** [comment]
alright ill try an figure out how to compile a jar and see if your fix worked

**Comment by thiakil** [comment]
released on https://minecraft.curseforge.com/projects/mekanism/files/2699534
let us know of any issues

**Comment by mlugg** [comment]
I think this is probably the same bug: I just tried to make a Turbine multiblock in a singleplayer world, once it was completed and the red particles appeared I immediately got a ticking block entity crash and now can't load that world. I do have a bunch of other mods, but I doubt they're causing it - I can try without if it helps? Crash report at https://termbin.com/jxz2

**Comment by mlugg** [comment]
(Pinging @thiakil so he knows about the potentially related issue)

**Comment by mlugg** [comment]
Wait, digging through source code and commits I just realized this was actually fixed a few days ago. Sorry!
