### ISSUE TITLE
Server crash Ticking GridNode

### ISSUE THREAD

**Issue by bigenergy** [mekanism-mod/Mekanism#5392]
#### Issue description:
Server crash on start

#### Steps to reproduce:
1. Start server
2. Get crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2814
**Mekanism:** 9.7.0.369

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/7xNSfC1c

**Comment by pupnewfster** [comment]
It seems I forgot the fact when I was reusing code about it being possible to attempt to insert things to a machine that do not have a recipe. I will take a look into this later today, as well as, improve the performance a bit more of autosort.

**Comment by thiakil** [comment]
released on https://minecraft.curseforge.com/projects/mekanism/files/2699534
