### ISSUE TITLE
Server tick loop TileEntityFactory

### ISSUE THREAD

**Issue by bigenergy** [mekanism-mod/Mekanism#5394]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server crash

#### Steps to reproduce:
unknown

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2814
**Mekanism:** 9.7.0.369

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/T0VbGuC6

**Comment by pupnewfster** [comment]
Duplicate/same crash/cause as #5392
