### ISSUE TITLE
[Suggestion] CraftTweaker getGas utility method

### ISSUE THREAD

**Issue by justinrusso** [mekanism-mod/Mekanism#5397]
**Describe the feature you'd like**
Essentially, I'd love for https://github.com/mekanism-mod/Mekanism/blob/1.12/src/main/java/mekanism/common/integration/crafttweaker/gas/GasBracketHandler.java#L33 this method to be exposed to crafttweaker. This will allow you to get a Gas more dynamically in scripts.

**Comment by thiakil** [comment]
Released on https://minecraft.curseforge.com/projects/mekanism/files/2699534
