### ISSUE TITLE
Description: Ticking block entity (With Dynamic Tank Multiblock)

### ISSUE THREAD

**Issue by JonMaker050** [mekanism-mod/Mekanism#5404]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Client Crash Description: Ticking block entity

TileEntityMultiblock.onUpdate

#### Steps to reproduce:
1. When approaching the Tank
2. Client Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.12.2 2814
**Mekanism:** 9.7
**Other relevant version:** 

https://pastebin.com/FUnPHvRA

**Comment by thiakil** [comment]
#5392

*Please* search for existing issues
